#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\VINRequest\Index.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 2 "..\..\Views\VINRequest\Index.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/VINRequest/Index.cshtml")]
    public partial class _Views_VINRequest_Index_cshtml : System.Web.Mvc.WebViewPage<GridViewModel<Webmall.Model.Entities.User.VINRequest>>
    {
        public _Views_VINRequest_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\VINRequest\Index.cshtml"
  
    ViewBag.Title = SharedResources.VINRequests;
    Layout = "~/Views/Shared/_PersonalLayout.cshtml";
    ViewBag.HideTitle = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1");

WriteLiteral(" class=\"main-title\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\VINRequest\Index.cshtml"
                  Write(SharedResources.VINRequests);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n<header");

WriteLiteral(" class=\"orders-header-controls d-md-none\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"orders-filter-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n        <svg");

WriteLiteral(" class=\"icon icon-sliders-h orders-filter-toggle__icon\"");

WriteLiteral(">\r\n            <use");

WriteAttribute("href", Tuple.Create(" href=\"", 487), Tuple.Create("\"", 557)
            
            #line 13 "..\..\Views\VINRequest\Index.cshtml"
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#sliders-h")
            
            #line default
            #line hidden
, 494), false)
);

WriteLiteral("></use>\r\n        </svg>");

            
            #line 14 "..\..\Views\VINRequest\Index.cshtml"
         Write(SharedResources.Filters);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </a>\r\n</header>\r\n");

            
            #line 17 "..\..\Views\VINRequest\Index.cshtml"
   Html.RenderPartial("_VinRequestFilter"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"card-specification-section\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\VINRequest\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\VINRequest\Index.cshtml"
     using (Html.BeginForm("RemoveRequest", "VinRequest"))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"table-responsive d-none d-md-block\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"spec-payment-table\"");

WriteLiteral(" id=\"spec-payment-table\"");

WriteLiteral(">\r\n                <thead");

WriteLiteral(" class=\"spec-payment-table__thead\"");

WriteLiteral(">\r\n                    <tr");

WriteLiteral(" class=\"spec-payment-table__tr\"");

WriteLiteral(">\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th spec-payment-table__number\"");

WriteLiteral("> ");

            
            #line 26 "..\..\Views\VINRequest\Index.cshtml"
                                                                                  Write(Html.SortColumnLink(Model, SharedResources.Number, "Id"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\VINRequest\Index.cshtml"
                                                      Write(Html.SortColumnLink(Model, SharedResources.RequestDate, "SendDate"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th spec-payment-table__vin\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\VINRequest\Index.cshtml"
                                                                              Write(Html.SortColumnLink(Model, SharedResources.AutoVINCode, "VIN"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\VINRequest\Index.cshtml"
                                                      Write(Html.SortColumnLink(Model, SharedResources.AutoMarka, "MarkaName"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\VINRequest\Index.cshtml"
                                                      Write(Html.SortColumnLink(Model, SharedResources.AutoModel, "ModelName"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th spec-payment-table__modif\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\VINRequest\Index.cshtml"
                                                                                Write(Html.SortColumnLink(Model, SharedResources.AutoModification, "ModifName"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\VINRequest\Index.cshtml"
                                                      Write(Html.SortColumnLink(Model, SharedResources.YearOfProduce, "Year"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"spec-payment-table__th\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\VINRequest\Index.cshtml"
                                                      Write(Html.SortColumnLink(Model, SharedResources.Responce, "IsRepsonded"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th></th>\r\n                    </tr>\r\n            " +
"    </thead>\r\n                <tbody");

WriteLiteral(" class=\"spec-payment-table__tbody\"");

WriteLiteral(">\r\n");

            
            #line 38 "..\..\Views\VINRequest\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\VINRequest\Index.cshtml"
                     foreach (var item in Model.List)
                    {
                        //string click = "onclick=\"document.location.href='" + Url.Action("ViewRequest", new { id = item.Id }) + "'\"";

            
            #line default
            #line hidden
WriteLiteral("                        <tr");

WriteLiteral(" class=\"spec-payment-table__tr comp-act-row\"");

WriteLiteral(">\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value-primary\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2751), Tuple.Create("\"", 2806)
            
            #line 43 "..\..\Views\VINRequest\Index.cshtml"
        , Tuple.Create(Tuple.Create("", 2758), Tuple.Create<System.Object, System.Int32>(Url.Action("ViewRequest", new { id = item.Id })
            
            #line default
            #line hidden
, 2758), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Views\VINRequest\Index.cshtml"
                                                                                                                                      Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(item.SendDate.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3216), Tuple.Create("\"", 3271)
            
            #line 49 "..\..\Views\VINRequest\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3223), Tuple.Create<System.Object, System.Int32>(Url.Action("ViewRequest", new { id = item.Id })
            
            #line default
            #line hidden
, 3223), false)
);

WriteLiteral(">");

            
            #line 49 "..\..\Views\VINRequest\Index.cshtml"
                                                                                                                             Write(item.VIN);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 52 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(item.MarkaName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(item.ModelName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 58 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(item.ModifName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(item.Year);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                            <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">\r\n");

            
            #line 65 "..\..\Views\VINRequest\Index.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\VINRequest\Index.cshtml"
                                     if (item.IsRepsonded)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span");

WriteAttribute("title", Tuple.Create(" title=\"", 4382), Tuple.Create("\"", 4478)
            
            #line 67 "..\..\Views\VINRequest\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4390), Tuple.Create<System.Object, System.Int32>(@item.AnswerDate.HasValue ? @item.AnswerDate.Value.ToShortDateString() : String.Empty
            
            #line default
            #line hidden
, 4390), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 68 "..\..\Views\VINRequest\Index.cshtml"
                                       Write(SharedResources.Yes);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span>\r\n");

            
            #line 70 "..\..\Views\VINRequest\Index.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n                            </td>\r\n      " +
"                      <td");

WriteLiteral(" class=\"spec-payment-table__td\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"spec-payment-table__value\"");

WriteLiteral(">");

            
            #line 74 "..\..\Views\VINRequest\Index.cshtml"
                                                                  Write(Html.CheckBox("delete", new { Value = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </td>\r\n                        </tr>\r\n");

            
            #line 77 "..\..\Views\VINRequest\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"spec d-md-none\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"spec__title\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\VINRequest\Index.cshtml"
                                Write(SharedResources.VINRequests);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 84 "..\..\Views\VINRequest\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\VINRequest\Index.cshtml"
             if (Model.List != null)
            {
                foreach (var item in Model.List)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"spec__product\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"spec__heading\"");

WriteLiteral(">");

            
            #line 89 "..\..\Views\VINRequest\Index.cshtml"
                                              Write(SharedResources.Number);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 89 "..\..\Views\VINRequest\Index.cshtml"
                                                                        Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteLiteral(" class=\"spec__main\"");

WriteLiteral(">\r\n                            <dl");

WriteLiteral(" class=\"spec__params\"");

WriteLiteral(">\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 92 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.AutoVINCode);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\VINRequest\Index.cshtml"
                                                   Write(item.VIN);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 94 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.RequestDate);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 95 "..\..\Views\VINRequest\Index.cshtml"
                                                    Write(item.SendDate.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 96 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.AutoMarka);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\VINRequest\Index.cshtml"
                                                    Write(item.MarkaName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 98 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.AutoModel);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 99 "..\..\Views\VINRequest\Index.cshtml"
                                                   Write(item.ModelName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 100 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.AutoModification);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 101 "..\..\Views\VINRequest\Index.cshtml"
                                                   Write(item.ModifName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 102 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.YearOfProduce);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 103 "..\..\Views\VINRequest\Index.cshtml"
                                                   Write(item.Year);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                                <dt");

WriteLiteral(" class=\"spec__property\"");

WriteLiteral("><strong>");

            
            #line 104 "..\..\Views\VINRequest\Index.cshtml"
                                                              Write(SharedResources.Responce);

            
            #line default
            #line hidden
WriteLiteral("</strong></dt>\r\n                                <dd");

WriteLiteral(" class=\"spec__value\"");

WriteLiteral(">");

            
            #line 105 "..\..\Views\VINRequest\Index.cshtml"
                                                    Write(item.IsRepsonded ? @SharedResources.Yes : "");

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                            </dl>\r\n                        </div>\r\n       " +
"             </div>\r\n");

            
            #line 109 "..\..\Views\VINRequest\Index.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 112 "..\..\Views\VINRequest\Index.cshtml"

        {Html.RenderPartial("Components/Pagination", Model);}


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("></div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"section-area__footer\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 117 "..\..\Views\VINRequest\Index.cshtml"
       Write(Html.SubmitButton(SharedResources.Delete,
                new
                {
                    onclick = string.Format("if (!confirm('"+SharedResources.AreYouSure+"')) return false; ", Url.Action("RemoveRequest")),
                    @class = "btn btn--reverse"
                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 123 "..\..\Views\VINRequest\Index.cshtml"
       Write(Html.Button(SharedResources.NewRequest,
                new
                {
                    onclick = string.Format("document.location.href = '{0}'; return false; ", Url.Action("NewRequest")),
                    @class = "btn btn--main"
                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 130 "..\..\Views\VINRequest\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

            
            #line 134 "..\..\Views\VINRequest\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\VINRequest\Index.cshtml"
      
        Html.RenderPartial("GridViewFooterScripts", Model);
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
