#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_FilterScripts.cshtml")]
    public partial class _Views_Shared__FilterScripts_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.ViewModel.Catalog.CatalogFilterViewModel>
    {
        public _Views_Shared__FilterScripts_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function() {
        //let priceRange = document.getElementById('priceRange');
        //let inputNumberA = document.getElementById('priceMin');
        //let inputNumberB = document.getElementById('priceMax');
        //let inputs = [inputNumberA, inputNumberB];

        ");

WriteLiteral(@"
        /* Filter-Slider */

        /* Filter-Badge*/
        $("".filter-badge__remove"").click(function() {
            var id = $(this).data(""id"");
            $(""#opt-"" + id + """").prop('checked', false);
            $("".filter-badges"").find(`[data-id='${id}']`).remove();
            submitFilter();
        });

        $(""#auto-selection-filter button"").click(function (e) {

            var clear = false;
            if (e.target.type == ""button"") {
                clear = true;
            }
            var filterForm = document.getElementById(""filterForm"");

            $(filterForm).children(""#markaId"").val(clear ? -1 : $('[name=""AutoMark""]').val());
            $(filterForm).children(""#modelId"").val(clear ? null : $('#AutoModel').combotree('getValue'));
            var modifId = $('#AutoModif').combotree('getValue');
            $(filterForm).children(""#modif"").val(clear ? null : modifId);
            if (modifId > 0 || window.user_IsGross) {
                document.getElementById(""filterForm"").submit();
            }
            return false;
        });

        $(""[name='query']"").bind(""change keyup input paste"", filterSection);
        $(""[name='query']"").keydown(preventSubmit);
    });

    function submitFilter(prepareFilter) {
        ");

WriteLiteral(@"

        if (prepareFilter)
            prepareFilter();

        let tempArray = document.location.href.split(""?"");
        if (tempArray[0].search(""/Search"") != -1) {
            var input = document.createElement(""input"");
            input.type = ""hidden"";
            input.name = ""Search"";
            input.value = """);

            
            #line 86 "..\..\Views\Shared\_FilterScripts.cshtml"
                       Write(Model?.Search);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            document.getElementById(\"searchParam\").name = \"\";\r\n            do" +
"cument.getElementById(\"filterForm\").appendChild(input);\r\n        }\r\n\r\n        do" +
"cument.getElementById(\"locker\").style.display = \"block\";\r\n        document.getEl" +
"ementById(\"filterForm\").submit();\r\n        return false;\r\n    }\r\n\r\n    function " +
"resetFilter() {\r\n        var tempArray = document.location.href.split(\"?\");\r\n   " +
"     var urlParams = tempArray[1].split(\'&\');\r\n        var baseUrl = tempArray[0" +
"];\r\n        var baseUrlParams = \'\';\r\n        for (var i = 0; i < urlParams.lengt" +
"h; i++) {\r\n            var pair = urlParams[i].split(\"=\");\r\n            if ((pai" +
"r[0] == \'modif\' || pair[0] == \'wareGroupId\' || pair[0] == \'groupId\' || pair[0] =" +
"= \'markaId\' || pair[0] == \'modelId\' || pair[0] == \'searchString\' || pair[0] == \'" +
"searchType\' || pair[0] == \'Search\') && pair[1] != null && pair[1] != \"\")\r\n      " +
"          baseUrlParams = baseUrlParams + \'&\' + urlParams[i];\r\n        }\r\n      " +
"  if (baseUrlParams)\r\n            baseUrl += `?${baseUrlParams.substring(1)}`;\r\n" +
"        document.location.href = baseUrl;\r\n        return false;\r\n    }\r\n\r\n    f" +
"unction filterSection(event) {\r\n        event.preventDefault();\r\n        event.s" +
"topPropagation();\r\n        var value = event.target.value;\r\n\r\n        var body =" +
" event.target.closest(\".filter__body\");\r\n        var elements = $(body).children" +
"(\".checkbox-label\");\r\n\r\n        if (!value) {\r\n            elements.css(\"display" +
"\", \"\");\r\n            $(body).children(\'.filter__more-options\').show();\r\n        " +
"    $(body).children(\".checkbox-label._is-field-off\").addClass(\"is-field-off\");\r" +
"\n            $(body).children(\".checkbox-label._is-field-off\").removeClass(\"_is-" +
"field-off\");\r\n            return;\r\n        }\r\n        elements.hide();\r\n        " +
"$(body).children(\".checkbox-label.is-field-off\").addClass(\"_is-field-off\");\r\n   " +
"     $(body).children(\".checkbox-label.is-field-off\").removeClass(\"is-field-off\"" +
");\r\n        $(body).children(\'.filter__more-options\').hide();\r\n        elements." +
"each(function (index, el) {\r\n            var label = $(el).children(\"label\")[0];" +
"\r\n            if (label.textContent.toLowerCase().includes(value.toLowerCase()))" +
" {\r\n                $(el).show();\r\n            }\r\n        });\r\n    }\r\n\r\n    func" +
"tion preventSubmit(event) {\r\n        if (event.keyCode === 13) {\r\n            ev" +
"ent.preventDefault();\r\n            event.target.dispatchEvent(new Event(\"change\"" +
"));\r\n            return false;\r\n        }\r\n        return true;\r\n    }\r\n\r\n</scri" +
"pt>\r\n");

        }
    }
}
#pragma warning restore 1591
