#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\_WareListScripts.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 2 "..\..\Views\Shared\_WareListScripts.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_WareListScripts.cshtml"
    using Webmall.UI.Core.Helpers;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_WareListScripts.cshtml")]
    public partial class _Views_Shared__WareListScripts_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__WareListScripts_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\_WareListScripts.cshtml"
  
    //var valute = SessionHelper.CurrentValute;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    document._action_GetWareProps = \'");

            
            #line 8 "..\..\Views\Shared\_WareListScripts.cshtml"
                                Write(Url.Action("ShortProperties", "CatalogService"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    document._action_GetWareReplacements = \'");

            
            #line 9 "..\..\Views\Shared\_WareListScripts.cshtml"
                                       Write(Url.Action("Analogs", "CatalogService"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    document._action_GetWareActionInfo = \'");

            
            #line 10 "..\..\Views\Shared\_WareListScripts.cshtml"
                                     Write(Url.Action("GetWareActionInfo", "CatalogService"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n    var timer;\r\n    $(\".product, .product-card\").mouseenter(function () {\r\n" +
"        var prod = this;\r\n        timer = setTimeout(function () {\r\n            " +
"stockMainDocsHoverHandlerUpdate(prod);\r\n        }, 500);\r\n    }).mouseleave(func" +
"tion () {\r\n        clearTimeout(timer);\r\n    });\r\n\r\n    function dataDealerToggl" +
"eHandlerUpdate (e) {\r\n        const parent = e.target.closest(\'.spec__product\');" +
"\r\n        const toggleName = this.dataset.dealerToggle;\r\n        const dropInfoB" +
"lock = childrenMatches(parent, \"[data-dealer=\'\" + toggleName + \"\']\")[0];\r\n\r\n    " +
"    if (dropInfoBlock && dropInfoBlock.dataset.loaded != \'true\') {\r\n            " +
"switch (toggleName) {\r\n                case \"spec\":\r\n                    UpdateS" +
"pecs(this.dataset.wareId, dropInfoBlock, \'div_\');\r\n                    break;\r\n " +
"               case \"similar\":\r\n                    UpdateAnaloguesInList(this.d" +
"ataset.wareId, dropInfoBlock, \'div_\');\r\n                    break;\r\n            " +
"}\r\n        }\r\n    }\r\n\r\n    function stockMainDocsHoverHandlerUpdate(product) {\r\n" +
"        let div = product.closest(\'div\');\r\n\r\n        let dropInfoBlock = div.que" +
"rySelector(\'.product__params, .product-card__params\');\r\n        if (dropInfoBloc" +
"k == null && getNextSibling) {\r\n            dropInfoBlock = getNextSibling(div, " +
"\'.product__footer\').querySelector(\'.product__params, .product-card__params\');\r\n " +
"       }\r\n\r\n        if (dropInfoBlock && dropInfoBlock.dataset.loaded != \'true\')" +
" {\r\n            UpdateSpecs(dropInfoBlock.dataset.wareId, dropInfoBlock, \'tile\')" +
";\r\n        }\r\n    }\r\n\r\n    function stockTableDocsClickHandlerUpdate(link) {\r\n  " +
"      let div = this.closest(\'div\');\r\n        let dropInfoBlock = div.querySelec" +
"tor(\'.spec-table-params__list\');\r\n        if (dropInfoBlock && dropInfoBlock.dat" +
"aset.loaded != \'true\') {\r\n            UpdateSpecs(dropInfoBlock.dataset.wareId, " +
"dropInfoBlock, link.currentTarget.typeParam);\r\n        }\r\n    }\r\n\r\n    function " +
"stockTableAnalogsClickHandlerUpdate(link) {\r\n        let tr = this.closest(\'tr\')" +
";\r\n\r\n        let dropInfoBlock = tr.nextElementSibling.querySelector(\'.product-l" +
"ine__analogs-list .manual-params\');\r\n        if (dropInfoBlock == null && getNex" +
"tSibling) {\r\n            dropInfoBlock = getNextSibling(tr, \'.stock-table__more\'" +
").querySelector(\'.product-line__analogs-list .manual-params\');\r\n        }\r\n\r\n   " +
"     if (dropInfoBlock && dropInfoBlock.dataset.loaded != \'true\') {\r\n           " +
" UpdateAnaloguesInList(dropInfoBlock.dataset.wareId, dropInfoBlock, \'table_\');\r\n" +
"        }\r\n    }\r\n\r\n    $(function () {\r\n        $(\'#gallerySortColumn\').change(" +
"resort);\r\n        $(\'#gallerySortDirection\').change(resort);\r\n        $(\'#brandF" +
"ilter\').change(resort);\r\n        $(\'#currentWarehouse\').change(function () {\r\n  " +
"          var id = $(\'#currentWarehouse\').val();\r\n            var url = \'");

            
            #line 79 "..\..\Views\Shared\_WareListScripts.cshtml"
                  Write(Url.Action("ChangeCurrentWarehouse", "Security"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var currentUrl = \'");

            
            #line 80 "..\..\Views\Shared\_WareListScripts.cshtml"
                         Write(Server.UrlEncode(ViewContext.RequestContext.HttpContext.Request.RawUrl));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            document.location.href = url + \"?id=\" + id + \"&returnUrl=\" + curr" +
"entUrl;\r\n        });\r\n        $(\"#extView\").bind(\'change\', function () {\r\n      " +
"      $(this).is(\":checked\") ? showImages() : hideImages();\r\n        });\r\n\r\n    " +
"    var showImg = $.cookie(\'VALMI_SHOW_IMAGES\');\r\n        if (showImg == null) s" +
"howImg = \'true\';\r\n        showImg = showImg == \'true\';\r\n\r\n        if ((showImg) " +
"&& ($(\"#extView\").attr(\"checked\"))) {\r\n            showImages();\r\n            $(" +
"\"#extView\").trigger(\"change\");\r\n        }\r\n        else {\r\n            $(\"#extVi" +
"ew\").attr(\"checked\", showImg).trigger(\"change\");\r\n        };\r\n\r\n        document" +
".querySelectorAll(\'[data-dealer-toggle]\').forEach(function (toggle) {\r\n         " +
"   toggle.addEventListener(\'click\', dataDealerToggleHandlerUpdate);\r\n        });" +
"\r\n\r\n        document.querySelectorAll(\'.spec-table-params__trigger\').forEach((li" +
"nk) => {\r\n            link.addEventListener(\'click\', stockTableDocsClickHandlerU" +
"pdate);\r\n            link.typeParam = \'table\';\r\n        });\r\n\r\n        document." +
"querySelectorAll(\'.spec__preview-specs\').forEach((link) => {\r\n            link.a" +
"ddEventListener(\'click\', stockTableDocsClickHandlerUpdate);\r\n            link.ty" +
"peParam = \'mobTable\';\r\n        });\r\n\r\n         document.querySelectorAll(\'.stock" +
"-table__analogs\').forEach((link) => {\r\n                link.addEventListener(\'cl" +
"ick\', stockTableAnalogsClickHandlerUpdate);\r\n            });\r\n    });\r\n\r\n    fun" +
"ction setview(view) {\r\n        document.location.href = Url.set(document.locatio" +
"n.href, \'view\', view);\r\n    }\r\n\r\n    function resort(col) {\r\n        $(\'#SortCol" +
"umn\').val(col);\r\n        window.SortByColumn(this, col, true, false);\r\n    }\r\n\r\n" +
"    function resortMobile(col, direction) {\r\n        $(\'#SortColumn\').val(col);\r" +
"\n        window.SortByColumn(this, col, true, null, direction);\r\n    }\r\n\r\n    va" +
"r isPrivate = true;\r\n    $(function () {\r\n        isPrivate = ($.cookie(\'");

            
            #line 134 "..\..\Views\Shared\_WareListScripts.cshtml"
                          Write(CommonHelpers.PrivateCookieName);

            
            #line default
            #line hidden
WriteLiteral("\') == \"true\" && \'");

            
            #line 134 "..\..\Views\Shared\_WareListScripts.cshtml"
                                                                            Write(SessionHelper.CurrentUser!=null && SessionHelper.IsGross);

            
            #line default
            #line hidden
WriteLiteral("\' == \'True\');\r\n        setYourPriceVisibility();\r\n    });\r\n\r\n    function switchP" +
"riceVs() {\r\n        isPrivate = !isPrivate;\r\n        setYourPriceVisibility();\r\n" +
"        $.cookie(\'");

            
            #line 141 "..\..\Views\Shared\_WareListScripts.cshtml"
             Write(CommonHelpers.PrivateCookieName);

            
            #line default
            #line hidden
WriteLiteral(@"', isPrivate, { expires: 365 });
    }

    function setYourPriceVisibility() {
        if (isPrivate) {
            $('th.view,td.price').hide();
            $('.ware-price').css(""display"", ""none"");
            $('.ware-retail-price').css(""display"", ""inline"");
            //$('td.price').hide();
            $('th.hide').removeClass('slim');
            ");

WriteLiteral("\r\n            $(\'th.hide\').html(\'<span onclick=\"switchPriceVs()\" title=\"");

            
            #line 152 "..\..\Views\Shared\_WareListScripts.cshtml"
                                                                 Write(SharedResources.ShowPrices);

            
            #line default
            #line hidden
WriteLiteral("\">");

            
            #line 152 "..\..\Views\Shared\_WareListScripts.cshtml"
                                                                                              Write(SharedResources.QntOnStock);

            
            #line default
            #line hidden
WriteLiteral(@"</span>');
        } else {
            $('th.view,td.price,.ware-price').show();
            $('.ware-price').css(""display"", ""inline"");
            $('.ware-retail-price').css(""display"", ""none"");
            $('th.hide').addClass('slim');
            $('th.hide').text('");

            
            #line 158 "..\..\Views\Shared\_WareListScripts.cshtml"
                          Write(SharedResources.QntOnStock);

            
            #line default
            #line hidden
WriteLiteral(@"');
        }
    }

    function showImages() {
        // переключение видимости первого столбца
        $('#wareList tr > *:nth-child(1)').show();
        $('.ware-action-img').hide();
        $.cookie('VALMI_SHOW_IMAGES', true);
    }

    function hideImages() {
        // переключение видимости первого столбца
        $('#wareList tr > *:nth-child(1)').hide();
        $('.ware-action-img').show();
        $.cookie('VALMI_SHOW_IMAGES', false);
    }

    function UpdateSpecs(wareId, dropInfoBlock, prefix) {
        updatePannel(document._action_GetWareProps + ""?wareId="" + wareId + ""&type="" + prefix, prefix + ""_spec_"" + wareId, null, function (d) { d.loaded = true; }, dropInfoBlock.dataset);
    }

    function UpdateAnaloguesInList(wareId, dropInfoBlock, prefix) {
        updatePannel(document._action_GetWareReplacements + ""?Id="" + wareId + ""&inTab=false"", prefix+""similar_"" + wareId, null, function (d) {
            d.loaded = true;
            document.querySelectorAll(""#similar_"" + wareId+' [data-dealer-toggle]').forEach(function (toggle) {
                toggle.addEventListener('click', dataDealerToggleHandler);
                toggle.addEventListener('click', dataDealerToggleHandlerUpdate);
            });
        }, dropInfoBlock.dataset);
    }

</script>");

        }
    }
}
#pragma warning restore 1591
