#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ComparisionMenu.cshtml")]
    public partial class _Views_Shared_ComparisionMenu_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.WareComparision.ComparisionList>
    {
        public _Views_Shared_ComparisionMenu_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\ComparisionMenu.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("<div");

WriteLiteral(" id=\"ComparePannel\"");

WriteLiteral(">\n");

            
            #line 7 "..\..\Views\Shared\ComparisionMenu.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Shared\ComparisionMenu.cshtml"
       Html.RenderPartial("ComparisionPannel", Model); 
            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\n    function RemoveComparision(id) {\n        updatePannel(\'");

            
            #line 12 "..\..\Views\Shared\ComparisionMenu.cshtml"
                 Write(Url.Action("RemoveComparision", "Catalog"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'?id=\' + id, \'ComparePannel\', null, checkComparisionPanalPresence);\n    }\n\n  " +
"  function AddComparision(id) {\n        updatePannel(\'");

            
            #line 16 "..\..\Views\Shared\ComparisionMenu.cshtml"
                 Write(Url.Action("AddComparision", "Catalog"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'?id=\' + id, \'ComparePannel\', null, checkComparisionPanalPresence);\n    }\n</s" +
"cript>");

        }
    }
}
#pragma warning restore 1591
