#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Layouts\_Header.cshtml"
    using Webmall.Model.Entities.Client;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 2 "..\..\Views\Shared\Layouts\_Header.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/_Header.cshtml")]
    public partial class _Views_Shared_Layouts__Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts__Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Layouts\_Header.cshtml"
  
    var breef = SessionHelper.CurrentUser != null ? SessionHelper.CurrentClient?.Breefing.Data : new BreefingData();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<header");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Shared\Layouts\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\Layouts\_Header.cshtml"
      Html.RenderAction("MainInformer", "Layout");
            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n");

            
            #line 11 "..\..\Views\Shared\Layouts\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\Layouts\_Header.cshtml"
      Html.RenderPartial("Components/TopHeaderNav");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"header-main\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-main__body\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\Layouts\_Header.cshtml"
                  Html.RenderPartial("Components/Logo");
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 17 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\Layouts\_Header.cshtml"
                  Html.RenderAction("TopMenu", "Layout", new { culture = UserPreferences.CurrentCulture });
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 18 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\Layouts\_Header.cshtml"
                 if (SessionHelper.CurrentUser == null)
                {
                    if (ViewBag.HideAuthorize != true)
                    {
                        Html.RenderPartial("Components/Authorize");
                    }
                }
                else
                {
                    Html.RenderAction("Authorized", "Layout", new { culture = UserPreferences.CurrentCulture });
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 30 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\Layouts\_Header.cshtml"
                  Html.RenderPartial("Components/MobUtils");
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 31 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\Layouts\_Header.cshtml"
                 if (ViewBag.BlockPayUpTo != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"header-alert is-warning d-none d-md-block\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Shared\Layouts\_Header.cshtml"
                                                                      Write(ViewBag.BlockPayUpTo);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 34 "..\..\Views\Shared\Layouts\_Header.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"header-meta-area\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-meta-area__body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"logo header-sticky-logo\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"logo__wrap\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"logo__img img-responsive\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1735), Tuple.Create("\"", 1781)
            
            #line 45 "..\..\Views\Shared\Layouts\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 1741), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/logo.svg")
            
            #line default
            #line hidden
, 1741), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"220\"");

WriteLiteral(" height=\"60\"");

WriteLiteral(">\r\n                    </span>\r\n                </div>\r\n\r\n");

            
            #line 49 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\Layouts\_Header.cshtml"
                  Html.RenderAction("GroupMenu", "Catalog", new { culture = UserPreferences.CurrentCulture });
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\Layouts\_Header.cshtml"
                  Html.RenderPartial("Components/SearchForm");
            
            #line default
            #line hidden
WriteLiteral("\r\n                ");

WriteLiteral("\r\n");

            
            #line 52 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\Layouts\_Header.cshtml"
                   Html.RenderAction("UserCars", "Layout"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                ");

WriteLiteral("\r\n\r\n");

            
            #line 55 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\Layouts\_Header.cshtml"
                 if (SessionHelper.CurrentUser == null)
                {
                    if (ViewBag.HideAuthorize != true)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"header__meta-link is-auth d-none\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"brand-catalogs header-meta-area__brand-catalogs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2568), Tuple.Create("\"", 2611)
            
            #line 60 "..\..\Views\Shared\Layouts\_Header.cshtml"
             , Tuple.Create(Tuple.Create("", 2575), Tuple.Create<System.Object, System.Int32>(Url.Action("Authorize", "Security")
            
            #line default
            #line hidden
, 2575), false)
);

WriteLiteral(">\r\n                                <svg");

WriteLiteral(" class=\"icon icon-logout-2 brand-catalogs__icon\"");

WriteLiteral(">\r\n                                    <use");

WriteAttribute("href", Tuple.Create(" href=", 2742), Tuple.Create("", 2810)
            
            #line 62 "..\..\Views\Shared\Layouts\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 2748), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#logout-2")
            
            #line default
            #line hidden
, 2748), false)
);

WriteLiteral("></use>\r\n                                </svg>\r\n                            </a>" +
"\r\n                        </div>\r\n");

            
            #line 66 "..\..\Views\Shared\Layouts\_Header.cshtml"
                    }
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"header__meta-link is-auth d-none\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"brand-catalogs header-meta-area__brand-catalogs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3158), Tuple.Create("\"", 3208)
            
            #line 71 "..\..\Views\Shared\Layouts\_Header.cshtml"
         , Tuple.Create(Tuple.Create("", 3165), Tuple.Create<System.Object, System.Int32>(Url.Action("EditPersonalData", "Security")
            
            #line default
            #line hidden
, 3165), false)
);

WriteLiteral(">\r\n                            <svg");

WriteLiteral(" class=\"icon icon-avatar brand-catalogs__icon\"");

WriteLiteral(">\r\n                                <use");

WriteAttribute("href", Tuple.Create(" href=", 3329), Tuple.Create("", 3395)
            
            #line 73 "..\..\Views\Shared\Layouts\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 3335), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#avatar")
            
            #line default
            #line hidden
, 3335), false)
);

WriteLiteral("></use>\r\n                            </svg>\r\n                        </a>\r\n      " +
"              </div>\r\n");

            
            #line 77 "..\..\Views\Shared\Layouts\_Header.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 79 "..\..\Views\Shared\Layouts\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Shared\Layouts\_Header.cshtml"
                   Html.RenderPartial("Components/CartHeader");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n");

            
            #line 85 "..\..\Views\Shared\Layouts\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\Shared\Layouts\_Header.cshtml"
      Html.RenderAction("ContactHeaderMob", "Layout", new { culture = UserPreferences.CurrentCulture });
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n");

            
            #line 89 "..\..\Views\Shared\Layouts\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Shared\Layouts\_Header.cshtml"
     if (breef.HaveDebt) { Html.RenderPartial("Components/AlertNotification"); }

            
            #line default
            #line hidden
WriteLiteral("\r\n</header>\r\n");

        }
    }
}
#pragma warning restore 1591
