#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 2 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/_TagsAfterBody.cshtml")]
    public partial class _Views_Shared_Layouts__TagsAfterBody_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts__TagsAfterBody_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
  
    var gtmAcc = ConfigHelper.GoogleTagManagerAccount;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
 if (!string.IsNullOrEmpty(gtmAcc))
{

            
            #line default
            #line hidden
WriteLiteral("    <!-- Google Tag Manager (noscript) -->\r\n");

WriteLiteral("    <noscript><iframe");

WriteAttribute("src", Tuple.Create(" src=\"", 242), Tuple.Create("\"", 301)
, Tuple.Create(Tuple.Create("", 248), Tuple.Create("https://www.googletagmanager.com/ns.html?id=", 248), true)
            
            #line 11 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
, Tuple.Create(Tuple.Create("", 292), Tuple.Create<System.Object, System.Int32>(gtmAcc
            
            #line default
            #line hidden
, 292), false)
);

WriteLiteral("\r\n                      height=\"0\"");

WriteLiteral(" width=\"0\"");

WriteLiteral(" style=\"display:none;visibility:hidden\"");

WriteLiteral("></iframe></noscript>\r\n");

WriteLiteral("    <!-- End Google Tag Manager (noscript) -->\r\n");

            
            #line 14 "..\..\Views\Shared\Layouts\_TagsAfterBody.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
