#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/CatalogHeaderControls.cshtml")]
    public partial class _Views_Shared_Layouts_CatalogHeaderControls_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.Catalog.CatalogWaresModel>
    {
        public _Views_Shared_Layouts_CatalogHeaderControls_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
  
    var pageSizes = new int[] { 12, 24, 36, 50 };
    var productSize = Model.Wares.List.Count;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
     if (Model.Wares.AllowPagging && Model.Wares.AllowPageSizeSelection)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"header-control\"");

WriteLiteral(">\r\n            <select");

WriteLiteral(" class=\"js-select-default show-by-select\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                 foreach (var item in pageSizes)
                {
                    var selected = (Model.Wares.PageSize == item) ? "SELECTED" : "";

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 543), Tuple.Create("\"", 556)
            
            #line 15 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
, Tuple.Create(Tuple.Create("", 551), Tuple.Create<System.Object, System.Int32>(item
            
            #line default
            #line hidden
, 551), false)
);

WriteLiteral(" ");

            
            #line 15 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                     Write(selected);

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                               Write(item);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 16 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n            <label");

WriteLiteral(" class=\"header-control__title\"");

WriteLiteral(" for=\"show-by-select-drop\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                                                      Write(SharedResources.ProductsPerPage);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        </div>\r\n");

            
            #line 20 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
     if (Model.TotalAmountWares > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"header-control d-none d-md-block\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-control__progress\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                             Write(SharedResources.Products);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 24 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                                                               Write(productSize);

            
            #line default
            #line hidden
WriteLiteral("</strong> ");

            
            #line 24 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                                                                                     Write(SharedResources.of);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 24 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
                                                                                                                                 Write(Model.TotalAmountWares);

            
            #line default
            #line hidden
WriteLiteral("</strong></div>\r\n        </div>\r\n");

            
            #line 26 "..\..\Views\Shared\Layouts\CatalogHeaderControls.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
