#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SelectionByAuto/_ModifInfoDialog.cshtml")]
    public partial class _Views_SelectionByAuto__ModifInfoDialog_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_SelectionByAuto__ModifInfoDialog_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"dialog-fiting\"");

WriteLiteral(" title=\"2.0 TDI\"");

WriteLiteral(@"></div>

<script>
        $(function() {

            $(""#dialog-fiting"").dialog({
                autoOpen: false,
                resizable: false,
                draggable: true,
                width: ""auto"",
                show: {
                    effect: ""fade"",
                    duration: 100
                },
                hide: {
                    effect: ""explode"",
                    duration: 500
                }
            }
            );
        });
    
        function ViewInfo(obj) {
            var title = $(obj).attr(""data-title""); //.parent().next().text();
            $('#dialog-fiting').dialog(""option"", ""title"", title);
            $(""#dialog-fiting"").dialog(""open"");
            $('#dialog-fiting').dialog(""widget"").position({
                my: ""left top"",
                at: ""right bottom"",
                of: $(obj)
            });
        }

        function UpdateInfo(obj) {
            var modifId = obj.id;
            updatePannel('");

            
            #line 36 "..\..\Views\SelectionByAuto\_ModifInfoDialog.cshtml"
                     Write(Url.Action("Info"));

            
            #line default
            #line hidden
WriteLiteral("\' + \'?modifId=\' + modifId, \'dialog-fiting\', null, ViewInfo, obj);\r\n        }\r\n\r\n<" +
"/script>");

        }
    }
}
#pragma warning restore 1591
