#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 2 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 4 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
    using Webmall.UI.Core.Helpers;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SelectionByAuto/GrossSelection.cshtml")]
    public partial class _Views_SelectionByAuto_GrossSelection_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.SelectionByAuto.SelectionByAutoMarkModel>
    {
        public _Views_SelectionByAuto_GrossSelection_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"content-secondary\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 9 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
   Write(SharedResources.SelectionByAuto);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    <div");

WriteLiteral(" class=\"select-auto-filter\"");

WriteLiteral(">\r\n        <table>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"filter-title\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(SharedResources.AutoMarka);

            
            #line default
            #line hidden
WriteLiteral(" (<a");

WriteAttribute("href", Tuple.Create(" href=\"", 396), Tuple.Create("\"", 425)
            
            #line 13 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
, Tuple.Create(Tuple.Create("", 403), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Auto")
            
            #line default
            #line hidden
, 403), false)
);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 426), Tuple.Create("\"", 538)
            
            #line 13 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                , Tuple.Create(Tuple.Create("", 436), Tuple.Create<System.Object, System.Int32>(string.Format("$.cookie('{0}', '', {{ expires: 365, path:'/' }})", CommonHelpers.LASTAUTO_COOKIENAME)
            
            #line default
            #line hidden
, 436), false)
);

WriteLiteral(">");

            
            #line 13 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                                                                                                                                                                                                  Write(SharedResources.AllBrands);

            
            #line default
            #line hidden
WriteLiteral("</a>)</td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
               Write(Html.DropDownListFor(m => m.AutoMark, Model.AutoMarkList.Select(i => new SelectListItem { Value = i.Id.ToString(CultureInfo.InvariantCulture), Text = i.Name }),
                             new
                             {
                                 @class = "easyui-combobox autocompletecombobox",
                                 data_options = "onSelect: AutoMarkSelected, onHidePanel: AutoMarkHidePannel",
                                 style = "display:none;"
                             }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"filter-title second-col\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                               Write(SharedResources.FuelType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
               Write(Html.DropDownList("fuelType", Model.FuelTypes,
                             new
                             {
                                 @class = "easyui-combobox",
                                 data_options = string.Format("valueField: 'Value', textField: 'Text', onSelect: FilterUpdate, panelHeight: 'auto', url: '{0}'", Url.Action("GetFuelTypes", "SelectionByAuto")),
                                 style = "display:none;"
                             }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
"");

WriteLiteral(" class=\"filter-title\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(SharedResources.AutoModel);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(Html.DropDownListFor(m => m.AutoModel, Model.AutoModelList.Select(i => new SelectListItem { Value = i.Id.ToString(CultureInfo.InvariantCulture), Text = i.Name }), new { style = "display:none;" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-title second-col\"");

WriteLiteral(">");

            
            #line 37 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                               Write(SharedResources.Power);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-value power\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
               Write(Html.TextBox("Power", null, new { onchange = "FilterUpdate()" }));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 39 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                                                                 Write(Html.DropDownList("powerMU",
new List<SelectListItem>
{
                                                    new SelectListItem {Text = SharedResources._HP, Value = "0", Selected = true},
                                                    new SelectListItem {Text = SharedResources._kWt, Value = "1", Selected = false}
}, new { @class = "easyui-combobox", style = "display: none; width:80px;", data_options = "onSelect: FilterUpdate, panelHeight: 'auto'" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <label><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" id=\"powerPercent\"");

WriteLiteral(" name=\"powerPercent\"");

WriteLiteral(" value=\"10\"");

WriteLiteral(" onchange=\"FilterUpdate()\"");

WriteLiteral(">+/- 10%</label>\r\n                </td>\r\n\r\n            </tr>\r\n            <tr>\r\n " +
"               <td");

WriteLiteral(" class=\"filter-title\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(SharedResources.YearOfProduce);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(Html.TextBox("YearOfProduce", null, new { onchange = "FilterUpdate()" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-title second-col\"");

WriteLiteral("></td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral("></td>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"filter-title\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(SharedResources.Volume);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
               Write(Html.TextBox("Volume", null, new { onchange = "FilterUpdate()" }));

            
            #line default
            #line hidden
WriteLiteral(" <span>/");

            
            #line 58 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                                                                         Write(SharedResources.cm3);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <label><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" id=\"volumePercent\"");

WriteLiteral(" name=\"volumePercent\"");

WriteLiteral(" value=\"10\"");

WriteLiteral(" onchange=\"FilterUpdate()\"");

WriteLiteral(">+/- 10%</label>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"filter-title second-col\"");

WriteLiteral("></td>\r\n                <td");

WriteLiteral(" class=\"filter-value\"");

WriteLiteral("></td>\r\n            </tr>\r\n        </table>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"modifications\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 72 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
Write(Scripts.Render("~/bundles/easyui"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    <script>\r\n        $(function() {\r\n\r\n            $(\'#");

            
            #line 78 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
           Write(Html.GetFullHtmlFieldNameFor(m => m.AutoModel));

            
            #line default
            #line hidden
WriteLiteral("\').combogrid({\r\n                width: 300,\r\n                panelWidth: 550,\r\n  " +
"              value: \'");

            
            #line 81 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                    Write(Model.AutoModel.HasValue ? Model.AutoModel : 0);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                mode: \'local\',\r\n                loadMsg: \"Loading..\",\r\n      " +
"          idField: \'Id\',\r\n                textField: \'Name\',\r\n                va" +
"lueField: \"Id\",\r\n                url: \'");

            
            #line 87 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                 Write(Url.Action("GetModelListByMark", "SelectionByAuto"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                queryParams: { markId: \'");

            
            #line 88 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                    Write(Model.AutoMark?.ToString() ?? Model.AutoMarkList.First().Id);

            
            #line default
            #line hidden
WriteLiteral("\' },\r\n                fitColumns: true,\r\n                columns: [\r\n            " +
"        [\r\n                        { field: \'Id\', title: \'Id\', hidden: true },\r\n" +
"                        { field: \'Name\', title: \'");

            
            #line 93 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                            Write(SharedResources.ModelOfCar);

            
            #line default
            #line hidden
WriteLiteral("\', width: 326 },\r\n                        { field: \'Start\', title: \'");

            
            #line 94 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                             Write(SharedResources.StartYear);

            
            #line default
            #line hidden
WriteLiteral("\', width: 101 },\r\n                        { field: \'End\', title: \'");

            
            #line 95 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                           Write(SharedResources.EndYear);

            
            #line default
            #line hidden
WriteLiteral("\', width: 101 }\r\n                    ]\r\n                ],\r\n                onSho" +
"wPanel: function() {\r\n                    this.oldValue = ");

            
            #line 99 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                Write(Model.AutoModel.HasValue ? Model.AutoModel : 0);

            
            #line default
            #line hidden
WriteLiteral(";\r\n                    if (!window.wasEmptied && ((this.oldValue == 0 && $(this)." +
"combogrid(\"getText\") == \'");

            
            #line 100 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                                                                                                  Write(SharedResources.SelectModel);

            
            #line default
            #line hidden
WriteLiteral(@"')
                        || (this.oldValue != 0 && this.oldValue == $(this).combogrid(""getValue"")))) {
                        this.oldText = $(this).combogrid(""getText"");
                        $(this).combogrid(""setText"", String.Empty);
                        window.wasEmptied = true;
                    }
                },
                onHidePanel: function() {
                    window.wasEmptied = false;
                    var newValue = $(this).combogrid(""getValue"");
                    if (newValue != this.oldValue) {
                        return false;
                    }
                    if (this.oldValue == 0) {
                        $(this).combogrid(""setText"", this.oldText);
                    }
                    return false;
                },
                onSelect: AutoModelSelected
            });

");

            
            #line 121 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
            
            
            #line default
            #line hidden
            
            #line 121 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
             if (Model.AutoModel.HasValue)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n        AutoModelSelected();\r\n        ");

WriteLiteral("\r\n");

            
            #line 126 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        });\r\n\r\n        function AutoMarkSelected(obj) {\r\n            var grid = $" +
"(\'#");

            
            #line 130 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                      Write(Html.GetFullHtmlFieldNameFor(m => m.AutoModel));

            
            #line default
            #line hidden
WriteLiteral("\').combogrid(\'grid\');\r\n            grid.datagrid({\r\n                queryParams: " +
"{\r\n                    markId: obj.value,\r\n                }\r\n            });\r\n " +
"           $(\'#");

            
            #line 136 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
           Write(Html.GetFullHtmlFieldNameFor(m => m.AutoModel));

            
            #line default
            #line hidden
WriteLiteral(@"').combogrid('setValue', 0);
            return false;
        }

        function AutoMarkHidePannel() {
            var data = $('#AutoMark').combobox('getData');
            var value = $('#AutoMark').combobox('getValue');
            data.forEach(function(item) {
                if (item.value == value) {
                    AutoMarkSelected(item);
                }
            });
            return false;
        }

        function AutoModelSelected() {
            $('input[name=""fuelType""]').val("""");
            FilterUpdate();

            var modelId = $('#");

            
            #line 155 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                         Write(Html.GetFullHtmlFieldNameFor(m => m.AutoModel));

            
            #line default
            #line hidden
WriteLiteral(@"').combotree('getValue');
            $('#fuelType').combobox({
                queryParams: {
                    modelId: modelId,
                }
            });

            return false;
        }

        function FilterUpdate() {
            var modelId = $('#");

            
            #line 166 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                         Write(Html.GetFullHtmlFieldNameFor(m => m.AutoModel));

            
            #line default
            #line hidden
WriteLiteral("\').combotree(\'getValue\');\r\n            var markId = $(\'#");

            
            #line 167 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                        Write(Html.GetFullHtmlFieldNameFor(m => m.AutoMark));

            
            #line default
            #line hidden
WriteLiteral(@"').val();

            var yearOfProduce = $('#YearOfProduce').val();
            var volume = $('#Volume').val();
            var volumePercent = $('#volumePercent').prop(""checked"") ? $('#volumePercent').val() : 0;
            var fuelType = $('input[name=""fuelType""]').val();
            var power = $('#Power').val();
            var powerMU = $('input[name=""powerMU""]').val();
            var powerPercent = $('#powerPercent').prop(""checked"") ? $('#powerPercent').val() : 0;

            var url = '");

            
            #line 177 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
                  Write(Url.Action("ModifList"));

            
            #line default
            #line hidden
WriteLiteral(@"' + '?markId=' + markId + '&modelId=' + modelId;
            url += (yearOfProduce) ? ""&yearOfProduce="" + yearOfProduce : """";
            url += (volume) ? ""&volume="" + volume : """";
            url += (volumePercent) ? ""&volumePercent="" + volumePercent : """";
            url += (fuelType) ? ""&fuelType="" + fuelType : """";
            url += (power) ? ""&power="" + power : """";
            url += (powerMU) ? ""&powerMU="" + powerMU : """";
            url += (powerPercent) ? ""&powerPercent="" + powerPercent : """";

            updatePannel(url, 'modifications');
        }

    </script>
");

});

WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 194 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
Write(Styles.Render("~/Content/easyuicss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("dialogs", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 199 "..\..\Views\SelectionByAuto\GrossSelection.cshtml"
Write(Html.Partial("_ModifInfoDialog"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
