#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
    using ValmiStore.Model.Entities.Order;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
    using Webmall.Model.Repositories.Abstract;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 4 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/_SummaryOrderInfo.cshtml")]
    public partial class _Views_Order__SummaryOrderInfo_cshtml : System.Web.Mvc.WebViewPage<Order>
    {
        public _Views_Order__SummaryOrderInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
  
    var selfDelivery = Model.Delivery == null || ((Model.Delivery.Id == null || Model.Delivery.Id == -1) && (Model.Delivery.DeliveryAddressId == null || Model.Delivery.DeliveryTypeId.ToLower() == "самовывоз"));
    var valute = SessionHelper.CurrentValute;
    var rate = (SessionHelper.Valutes.Count() > 1) ? valute.Rate : 1;
    var referenceRepository = DependencyResolver.Current.GetService<IReferenceRepository>();
    //var agreement = string.IsNullOrEmpty(Model.PayDelayName) ? string.Format("{0} {1}", Model.PayDelayDays, SharedResources.days) : Model.PayDelayName;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"orders-list\"");

WriteLiteral(">\r\n    <header");

WriteLiteral(" class=\"orders-list__header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orders-list__heading\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                     Write(SharedResources.SummaryListTitle);

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"orders-list__date\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                      Write(Model.OrderDate.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n    </header>\r\n    <div");

WriteLiteral(" class=\"table-responsive d-none d-md-block\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"orders-list__table\"");

WriteLiteral(">\r\n            <thead");

WriteLiteral(" class=\"orders-list__thead\"");

WriteLiteral(">\r\n                <tr");

WriteLiteral(" class=\"orders-list__tr\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.Number);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.WareName);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.UnitPrice);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.Amount);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.Sum);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 26 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                 Write(valute.Code);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" class=\"orders-list__th\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.FromWarehouse);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody");

WriteLiteral(" class=\"orders-list__tbody\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                   var sum = (Model.Delivery.Cost.HasValue) ? Model.Delivery.Cost.Value : decimal.Zero; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                 foreach (var pos in Model.Positions)
                {
                    sum += pos.Sum;

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteLiteral(" class=\"orders-list__tr\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral("><a");

WriteLiteral(" class=\"orders-list__order-number\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                             Write(pos.WareNumber);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"orders-list__product-brand\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                               Write(SharedResources.Producer);

            
            #line default
            #line hidden
WriteLiteral(": <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                      Write(pos.ProducerName);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n                            <div");

WriteLiteral(" class=\"orders-list__product-heading\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                             Write(pos.WareName);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n                        </td>\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral("><span");

WriteLiteral(" class=\"orders-list__price\"");

WriteLiteral(">");

            
            #line 41 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                Write(SessionHelper.PriceFormat(pos.Price / rate));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral("><span");

WriteLiteral(" class=\"orders-list__amount\"");

WriteLiteral(">");

            
            #line 42 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                 Write(string.Format("{0:0}", pos.WareQnt));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"orders-list__total-price\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                             Write(SessionHelper.PriceFormat(pos.Sum / rate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </td>\r\n                        <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral("><span");

WriteLiteral(" class=\"orders-list__stock\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                        </span></td>\r\n                    </tr>\r\n");

            
            #line 50 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n            <tfoot");

WriteLiteral(" class=\"orders-list__tfoot\"");

WriteLiteral(">\r\n");

            
            #line 53 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                 if (Model.Delivery.Cost > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(" class=\"orders-list__tr\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"orders-list__product-heading\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 58 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                           Write(SharedResources.Delivery);

            
            #line default
            #line hidden
WriteLiteral(" <b>");

            
            #line 58 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                         Write(SessionHelper.PriceFormat((Model.Delivery.Cost.HasValue) ? Model.Delivery.Cost.Value : decimal.Zero));

            
            #line default
            #line hidden
WriteLiteral("</b> ");

            
            #line 58 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                                                    Write(valute.Code);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n                        </td>\r\n           " +
"         </tr>\r\n");

            
            #line 62 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteLiteral(" class=\"orders-list__tr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                        </td>\r\n                    <td");

WriteLiteral(" class=\"orders-list__td\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"orders-list__total-price\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                         Write(SharedResources.OrderSum);

            
            #line default
            #line hidden
WriteLiteral(": <span");

WriteLiteral(" class=\"orders-list__total-price-value\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                 Write(SessionHelper.PriceFormat(sum / rate));

            
            #line default
            #line hidden
WriteLiteral("</span> <span");

WriteLiteral(" class=\"orders-list__total-price-currency\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                                                                                                               Write(valute.Code);

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                    </td>\r\n                </tr>\r\n            </tf" +
"oot>\r\n        </table>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"orders-list__mob d-md-none\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" class=\"orders-list__mob-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"orders-list__mob-heading\"");

WriteLiteral(">");

            
            #line 76 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                             Write(SharedResources.Number);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"orders-list__mob-heading\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                             Write(SharedResources.Sum);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 77 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                   Write(valute.Code);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </header>\r\n");

            
            #line 79 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
           sum = (Model.Delivery.Cost.HasValue) ? Model.Delivery.Cost.Value : decimal.Zero; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 80 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
        
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
         foreach (var pos in Model.Positions)
        {
            sum += pos.Sum;

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"orders-list__mob-order\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"orders-list__mob-side\"");

WriteLiteral("><a");

WriteLiteral(" class=\"orders-list__mob-order-number\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                Write(pos.WareNumber);

            
            #line default
            #line hidden
WriteLiteral("</a><span");

WriteLiteral(" class=\"orders-list__mob-order-date\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                                              Write(string.Format("{0:0}", pos.WareQnt));

            
            #line default
            #line hidden
WriteLiteral("x");

            
            #line 84 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                                                                                     Write(SessionHelper.PriceFormat(pos.Price / rate));

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                <div");

WriteLiteral(" class=\"orders-list__mob-side\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"orders-list__mob-price\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                   Write(SessionHelper.PriceFormat(pos.Sum / rate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <button");

WriteLiteral(" class=\"orders-list__mob-toggle\"");

WriteLiteral(">\r\n                        <svg");

WriteLiteral(" class=\"icon icon-chevron-down orders-list__mob-toggle-icon\"");

WriteLiteral(">\r\n                            <use");

WriteAttribute("href", Tuple.Create(" href=\"", 5717), Tuple.Create("\"", 5790)
            
            #line 89 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
, Tuple.Create(Tuple.Create("", 5724), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#chevron-down")
            
            #line default
            #line hidden
, 5724), false)
);

WriteLiteral("></use>\r\n                        </svg>\r\n                    </button>\r\n         " +
"       </div>\r\n                <div");

WriteLiteral(" class=\"orders-list__mob-more\"");

WriteLiteral(">\r\n                    <dl");

WriteLiteral(" class=\"orders-mob__params\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"orders-mob__param\"");

WriteLiteral(">\r\n                            <dt");

WriteLiteral(" class=\"orders-mob__param-term\"");

WriteLiteral(">");

            
            #line 96 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                          Write(SharedResources.WareName);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n                            <dd");

WriteLiteral(" class=\"orders-mob__param-definition\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                            Write(pos.WareName);

            
            #line default
            #line hidden
WriteLiteral("</a></dd>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"orders-mob__param\"");

WriteLiteral(">\r\n                            <dt");

WriteLiteral(" class=\"orders-mob__param-term\"");

WriteLiteral(">");

            
            #line 100 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                          Write(SharedResources.FromWarehouse);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n                            <dd");

WriteLiteral(" class=\"orders-mob__param-definition\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                            </dd>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"orders-mob__param\"");

WriteLiteral(">\r\n                            <dt");

WriteLiteral(" class=\"orders-mob__param-term\"");

WriteLiteral(">");

            
            #line 106 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                          Write(SharedResources.Producer);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n                            <dd");

WriteLiteral(" class=\"orders-mob__param-definition\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 107 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                            Write(pos.ProducerName);

            
            #line default
            #line hidden
WriteLiteral("</a></dd>\r\n                        </div>\r\n                    </dl>\r\n           " +
"     </div>\r\n            </div>\r\n");

            
            #line 112 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <footer");

WriteLiteral(" class=\"orders-list__mob-footer\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"orders-list__mob-summary\"");

WriteLiteral(">");

            
            #line 114 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(SharedResources.OrderSum);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            <div");

WriteLiteral(" class=\"orders-list__mob-total-price\"");

WriteLiteral("><span");

WriteLiteral(" class=\"orders-list__mob-total\"");

WriteLiteral(">");

            
            #line 115 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                      Write(SessionHelper.PriceFormat(sum / rate));

            
            #line default
            #line hidden
WriteLiteral("</span> ");

            
            #line 115 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                                                                                                                    Write(valute.Code);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            ");

WriteLiteral("\r\n        </footer>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"manual-params manual-params--bigger\"");

WriteLiteral(">\r\n        <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n            <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 121 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                        Write(SharedResources.PaymentConditions);

            
            #line default
            #line hidden
WriteLiteral(":</dt>\r\n            <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">30 дней</dd>\r\n        </dl>\r\n        <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n            <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 125 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                        Write(SharedResources.PaymentForm);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n            <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">");

            
            #line 126 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                            Write(Model.PaymentConditionsId == (int)PaymentConditions.Cash ? SharedResources.Cash : SharedResources.Cashless);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        </dl>\r\n        <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n            <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 129 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                        Write(SharedResources.DeliveryType);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n            <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                            Write(selfDelivery ? SharedResources.SelfDelivery + ", " + SharedResources.OrderIsAvailableForShipment + " " + Model.AvailabilityDatePresenter : Model.Delivery.DeliveryTypeId);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        </dl>\r\n        <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n            <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 133 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                        Write(SharedResources.DeliveryAddress);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n            <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">\r\n");

            
            #line 135 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                
            
            #line default
            #line hidden
            
            #line 135 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                  
                    string address;
                    if (selfDelivery)
                    {
                        var warehouses = referenceRepository.GetWarehouses(SessionHelper.CurrentClientId, UserPreferences.CurrentCulture);
                        var warehouse = warehouses.FirstOrDefault(i => i.Id == Model.WarehouseId);
                        address = warehouse == null ? Model.WarehouseName : warehouse.Address;
                    }
                    else
                    {
                        address = Model.Delivery.Address;
                    }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 148 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
            Write(address);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </dd>\r\n        </dl>\r\n        <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n            <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 152 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                        Write(SharedResources.Comment);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n            <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">");

            
            #line 153 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                           Write(Model.HtmlComment);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        </dl>\r\n");

            
            #line 155 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
        
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.CanNotBeChangedComment))
        {

            
            #line default
            #line hidden
WriteLiteral("            <dl");

WriteLiteral(" class=\"manual-params__param\"");

WriteLiteral(">\r\n                <dt");

WriteLiteral(" class=\"manual-params__value\"");

WriteLiteral(">");

            
            #line 158 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                            Write(SharedResources.Comment2);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n                <dd");

WriteLiteral(" class=\"manual-params__property\"");

WriteLiteral(">");

            
            #line 159 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
                                               Write(Model.CanNotBeChangedComment);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n            </dl>\r\n");

            
            #line 161 "..\..\Views\Order\_SummaryOrderInfo.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
