#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Order\List.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    #line 2 "..\..\Views\Order\List.cshtml"
    using Webmall.UI.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/List.cshtml")]
    public partial class _Views_Order_List_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.ViewModel.Order.OrdersListViewModel>
    {
        public _Views_Order_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Order\List.cshtml"
  
    Layout = "_OrderListLayout.cshtml";
    ViewBag.Title = SharedResources.Orders;
    //var hasTrusted = SessionHelper.CurrentUser.CurrentClient.Client.TrustedPersons != null && SessionHelper.CurrentUser.CurrentClient.Client.TrustedPersons.Any();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"stock-area is-table-view\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <button");

WriteLiteral(" class=\"filter-toggle stock-area__filter-toggle\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n        <svg");

WriteLiteral(" class=\"icon icon-funnel filter-toggle__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n            <use");

WriteAttribute("href", Tuple.Create(" href=\"", 713), Tuple.Create("\"", 780)
            
            #line 17 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 720), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#funnel")
            
            #line default
            #line hidden
, 720), false)
);

WriteLiteral("></use>\r\n        </svg>\r\n        <span");

WriteLiteral(" class=\"filter-toggle__text\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Order\List.cshtml"
                                     Write(SharedResources.Filters);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </button>\r\n    <div");

WriteLiteral(" class=\"stock-area__top-controls\"");

WriteLiteral(">\r\n        <!-- switcher-->\r\n        <div");

WriteLiteral(" class=\"stock-area__switcher switcher-label\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" class=\"switcher-label__input visually-hidden js-mode-trigger\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"has-option-1\"");

WriteLiteral("\r\n                   id=\"option-opt-1\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"switcher-label__main\"");

WriteLiteral(" for=\"option-opt-1\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Order\List.cshtml"
                                                              Write(SharedResources.LineByLine);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        </div>\r\n        <a");

WriteLiteral(" class=\"stock-area__back btn btn--primary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Order\List.cshtml"
                                                         Write(SharedResources.CreateReturn);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"stock-area__table\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"stock-table stock-area__table-main js-checked-all scrollbar is-table-mode" +
"\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"stock-table__header\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"stock-table__row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">&nbsp;</div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__checkbox checkbox-label\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" class=\"checkbox-label__input js-checked-all-trigger\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"is-opt-0\"");

WriteLiteral(" id=\"opt-0\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"checkbox-label__main\"");

WriteLiteral(" for=\"opt-0\"");

WriteLiteral("></label>\r\n                        </div>\r\n                    </div>\r\n          " +
"          <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 45 "..\..\Views\Order\List.cshtml"
                       Write(SharedResources.OrderNumber);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 50 "..\..\Views\Order\List.cshtml"
                       Write(SharedResources.DataAndTimeOrder);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">");

            
            #line 54 "..\..\Views\Order\List.cshtml"
                                                     Write(SharedResources.Status);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Order\List.cshtml"
                                                     Write(SharedResources.DeliveryDate);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Order\List.cshtml"
                                                     Write(SharedResources.Amount);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">");

            
            #line 63 "..\..\Views\Order\List.cshtml"
                                                     Write(SharedResources.Note);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__caption\"");

WriteLiteral(">");

            
            #line 66 "..\..\Views\Order\List.cshtml"
                                                     Write(SharedResources.Sum);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">&nbsp;</div>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"stock-table__main\"");

WriteLiteral(">\r\n");

            
            #line 72 "..\..\Views\Order\List.cshtml"
                
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Order\List.cshtml"
                 foreach (var item in Model.Orders.List)
                {
                    var status = Model.Statuses.FirstOrDefault(i => i.StatusId == item.StatusId);

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"stock-table__wrapper js-accordion\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"stock-table__row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" class=\"js-accordion-trigger stock-table__more\"");

WriteLiteral(" type=\"button\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 4228), Tuple.Create("\"", 4267)
, Tuple.Create(Tuple.Create("", 4238), Tuple.Create("OpenOrderItemProp(\'", 4238), true)
            
            #line 78 "..\..\Views\Order\List.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 4257), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 4257), false)
, Tuple.Create(Tuple.Create("", 4265), Tuple.Create("\')", 4265), true)
);

WriteLiteral(">\r\n                                    <svg");

WriteLiteral(" class=\"icon icon-chevron-down stock-table__more-icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                        <use");

WriteAttribute("href", Tuple.Create(" href=\"", 4435), Tuple.Create("\"", 4508)
            
            #line 80 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 4442), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#chevron-down")
            
            #line default
            #line hidden
, 4442), false)
);

WriteLiteral("></use>\r\n                                    </svg>\r\n                            " +
"    </button>\r\n                            </div>\r\n\r\n                           " +
" <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__checkbox checkbox-label\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"checkbox-label__input js-checked-all-item\"");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4908), Tuple.Create("\"", 4930)
, Tuple.Create(Tuple.Create("", 4915), Tuple.Create("is-opt-", 4915), true)
            
            #line 87 "..\..\Views\Order\List.cshtml"
                                          , Tuple.Create(Tuple.Create("", 4922), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 4922), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 4931), Tuple.Create("\"", 4948)
, Tuple.Create(Tuple.Create("", 4936), Tuple.Create("opt-", 4936), true)
            
            #line 87 "..\..\Views\Order\List.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 4940), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 4940), false)
);

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"checkbox-label__main\"");

WriteAttribute("for", Tuple.Create(" for=\"", 5023), Tuple.Create("\"", 5041)
, Tuple.Create(Tuple.Create("", 5029), Tuple.Create("opt-", 5029), true)
            
            #line 88 "..\..\Views\Order\List.cshtml"
 , Tuple.Create(Tuple.Create("", 5033), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 5033), false)
);

WriteLiteral("></label>\r\n                                </div>\r\n                            </" +
"div>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__text\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"stock-table__articul\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5322), Tuple.Create("\"", 5390)
            
            #line 93 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 5329), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "Order", new { orderId = item.Number })
            
            #line default
            #line hidden
, 5329), false)
);

WriteLiteral(">");

            
            #line 93 "..\..\Views\Order\List.cshtml"
                                                                                                                                    Write(item.Number);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                </div>\r\n                                <di" +
"v");

WriteLiteral(" class=\"stock-table__helpers\"");

WriteLiteral(">\r\n");

            
            #line 96 "..\..\Views\Order\List.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Order\List.cshtml"
                                     if (item.PaymentInfo.IsPayed)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"stock-table__helper badge\"");

WriteLiteral(" data-tippy-gray-content=\"Оплачено\"");

WriteLiteral(">\r\n                                            <svg");

WriteLiteral(" class=\"badge__icon\"");

WriteLiteral(" width=\"26\"");

WriteLiteral(" height=\"17\"");

WriteLiteral(" viewBox=\"0 0 26 17\"");

WriteLiteral(" fill=\"none\"");

WriteLiteral("\r\n                                                 xmlns=\"http://www.w3.org/2000/" +
"svg\"");

WriteLiteral(">\r\n                                                <rect");

WriteLiteral(" x=\"2\"");

WriteLiteral(" y=\"2\"");

WriteLiteral(" width=\"16\"");

WriteLiteral(" height=\"12\"");

WriteLiteral(" rx=\"2\"");

WriteLiteral(" fill=\"#49A122\"");

WriteLiteral("></rect>\r\n                                                <rect");

WriteLiteral(" x=\"2\"");

WriteLiteral(" y=\"4\"");

WriteLiteral(" width=\"16\"");

WriteLiteral(" height=\"1\"");

WriteLiteral(" fill=\"white\"");

WriteLiteral("></rect>\r\n                                                <path");

WriteLiteral(" d=\"M24.5938 10.5C24.5938 13.2614 22.3552 15.5 19.5938 15.5C16.8323 15.5 14.5938 " +
"13.2614 14.5938 10.5C14.5938 7.73858 16.8323 5.5 19.5938 5.5C22.3552 5.5 24.5938" +
" 7.73858 24.5938 10.5Z\"");

WriteLiteral("\r\n                                                      fill=\"#49A122\"");

WriteLiteral(" stroke=\"white\"");

WriteLiteral("></path>\r\n                                                <path");

WriteLiteral(@" d=""M19.6853 10.8302C19.3569 11.1201 19.0559 11.3899 19.0115 11.427L18.9328 11.4978L18.5942 11.164L17.2909 9.87898L16.9147 10.2499L16.5384 10.6208L18.1974 12.2565L18.8952 12.9444L18.9773 12.8803C19.1791 12.7218 22.6495 9.4624 22.6495 9.43879C22.6495 9.41519 21.9723 8.66661 21.9518 8.66661C21.9484 8.66661 20.0137 10.5402 19.6853 10.8302Z""");

WriteLiteral("\r\n                                                      fill=\"white\"");

WriteLiteral("></path>\r\n                                            </svg>\r\n                   " +
"                     </div>\r\n");

            
            #line 109 "..\..\Views\Order\List.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"stock-table__helper badge\"");

WriteLiteral(" data-tippy-gray-content=\"\"");

WriteLiteral(">\r\n                                        <svg");

WriteLiteral(" class=\"icon icon-info badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                            <use");

WriteAttribute("href", Tuple.Create(" href=\"", 7380), Tuple.Create("\"", 7445)
            
            #line 112 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 7387), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#info")
            
            #line default
            #line hidden
, 7387), false)
);

WriteLiteral("></use>\r\n                                        </svg>\r\n                        " +
"                <div");

WriteLiteral(" data-tippy-gray-content-template=\"\"");

WriteLiteral(">\r\n                                            <strong>");

            
            #line 115 "..\..\Views\Order\List.cshtml"
                                               Write(SharedResources.OrderAuthor);

            
            #line default
            #line hidden
WriteLiteral(":</strong>\r\n                                            <p>");

            
            #line 116 "..\..\Views\Order\List.cshtml"
                                          Write(item.UserName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        </div>\r\n                           " +
"         </div>\r\n                                </div>\r\n                       " +
"     </div>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                                <time");

WriteLiteral(" class=\"stock-table__date\"");

WriteAttribute("datetime", Tuple.Create(" datetime=\"", 8037), Tuple.Create("\"", 8107)
            
            #line 122 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 8048), Tuple.Create<System.Object, System.Int32>(item.OrderDate.Date.ToString(CultureInfo.CurrentUICulture)
            
            #line default
            #line hidden
, 8048), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 123 "..\..\Views\Order\List.cshtml"
                               Write(item.OrderDate.Date.ToString("dd.MM.yyyy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <span>");

            
            #line 124 "..\..\Views\Order\List.cshtml"
                                     Write(item.OrderDate.ToString("HH:mm"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </time>\r\n                            </d" +
"iv>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__badge status-badge is-processing\"");

WriteAttribute("style", Tuple.Create(" style=\"", 8516), Tuple.Create("\"", 8561)
, Tuple.Create(Tuple.Create("", 8524), Tuple.Create("background-color:", 8524), true)
            
            #line 128 "..\..\Views\Order\List.cshtml"
                                    , Tuple.Create(Tuple.Create(" ", 8541), Tuple.Create<System.Object, System.Int32>(status?.WebColor
            
            #line default
            #line hidden
, 8542), false)
);

WriteLiteral(">");

            
            #line 128 "..\..\Views\Order\List.cshtml"
                                                                                                                                    Write(item.StatusName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__text\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 132 "..\..\Views\Order\List.cshtml"
                                Write(item.DeliveryTime?.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"stock-table__helpers\"");

WriteLiteral(">\r\n");

            
            #line 135 "..\..\Views\Order\List.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 135 "..\..\Views\Order\List.cshtml"
                                     if (item.DeliveryInfo.DeliveryTypeId == 1)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"stock-table__helper badge\"");

WriteLiteral(" data-tippy-gray-content=\"\"");

WriteLiteral(">\r\n                                            <svg");

WriteLiteral(" class=\"icon icon-self-delivery badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 9337), Tuple.Create("\"", 9411)
            
            #line 139 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 9344), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#self-delivery")
            
            #line default
            #line hidden
, 9344), false)
);

WriteLiteral("></use>\r\n                                            </svg>\r\n                    " +
"                        <div");

WriteLiteral(" data-tippy-gray-content-template=\"\"");

WriteLiteral(">\r\n                                                <strong></strong>\r\n           " +
"                                     <p>");

            
            #line 143 "..\..\Views\Order\List.cshtml"
                                              Write(SharedResources.SelfDelivery);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                            </div>\r\n                       " +
"                 </div>\r\n");

            
            #line 146 "..\..\Views\Order\List.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteLiteral(" class=\"stock-table__helper badge\"");

WriteLiteral(" data-tippy-gray-content=\"\"");

WriteLiteral(">\r\n                                            <svg");

WriteLiteral(" class=\"icon icon-truck badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 10203), Tuple.Create("\"", 10269)
            
            #line 151 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 10210), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#truck")
            
            #line default
            #line hidden
, 10210), false)
);

WriteLiteral("></use>\r\n                                            </svg>\r\n                    " +
"                        <div");

WriteLiteral(" data-tippy-gray-content-template=\"\"");

WriteLiteral(">\r\n                                                <strong></strong>\r\n           " +
"                                     <p>");

            
            #line 155 "..\..\Views\Order\List.cshtml"
                                              Write(SharedResources.Delivery);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                            </div>\r\n                       " +
"                 </div>\r\n");

            
            #line 158 "..\..\Views\Order\List.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n                            </div>\r\n     " +
"                       <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__order-info\"");

WriteLiteral(" data-tippy-gray-content=\"\"");

WriteLiteral(">\r\n");

            
            #line 163 "..\..\Views\Order\List.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 163 "..\..\Views\Order\List.cshtml"
                                     foreach (var pos in item.PosStatuses)
                                    {
                                        var posStatus = Model.PosStatuses.FirstOrDefault(i => i.StatusId == pos.StatusId);

            
            #line default
            #line hidden
WriteLiteral("                                        <span");

WriteAttribute("style", Tuple.Create(" style=\"", 11237), Tuple.Create("\"", 11289)
, Tuple.Create(Tuple.Create("", 11245), Tuple.Create("color:", 11245), true)
            
            #line 166 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create(" ", 11251), Tuple.Create<System.Object, System.Int32>(posStatus?.WebColor ?? "0xFFFFFF"
            
            #line default
            #line hidden
, 11252), false)
, Tuple.Create(Tuple.Create("", 11288), Tuple.Create(";", 11288), true)
);

WriteLiteral(">");

            
            #line 166 "..\..\Views\Order\List.cshtml"
                                                                                              Write(pos.Qnt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 167 "..\..\Views\Order\List.cshtml"
                                        if (item.PosStatuses.Last() != pos)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            ");

WriteLiteral("/");

WriteLiteral("\r\n");

            
            #line 170 "..\..\Views\Order\List.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" data-tippy-gray-content-template=\"\"");

WriteLiteral(">\r\n");

            
            #line 173 "..\..\Views\Order\List.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 173 "..\..\Views\Order\List.cshtml"
                                         foreach (var pos in item.PosStatuses)
                                        {
                                            var posStatus = Model.PosStatuses.FirstOrDefault(i => i.StatusId == pos.StatusId);

            
            #line default
            #line hidden
WriteLiteral("                                            <p>");

            
            #line 176 "..\..\Views\Order\List.cshtml"
                                           Write(posStatus?.StatusName ?? pos.StatusName);

            
            #line default
            #line hidden
WriteLiteral(" - <strong");

WriteAttribute("style", Tuple.Create(" style=\"", 11999), Tuple.Create("\"", 12051)
, Tuple.Create(Tuple.Create("", 12007), Tuple.Create("color:", 12007), true)
            
            #line 176 "..\..\Views\Order\List.cshtml"
                                 , Tuple.Create(Tuple.Create(" ", 12013), Tuple.Create<System.Object, System.Int32>(posStatus?.WebColor ?? "0xFFFFFF"
            
            #line default
            #line hidden
, 12014), false)
, Tuple.Create(Tuple.Create("", 12050), Tuple.Create(";", 12050), true)
);

WriteLiteral(">");

            
            #line 176 "..\..\Views\Order\List.cshtml"
                                                                                                                                                    Write(pos.Qnt);

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\r\n");

            
            #line 177 "..\..\Views\Order\List.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </div" +
">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__comment custom-comment\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 183 "..\..\Views\Order\List.cshtml"
                               Write(item.Options.Comment);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"stock-table__cell text-center\"");

WriteLiteral(">\r\n                                <strong");

WriteLiteral(" class=\"stock-table__text\"");

WriteLiteral(">");

            
            #line 187 "..\..\Views\Order\List.cshtml"
                                                             Write(item.Sum);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"stock-table__cell\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"stock-table__control\"");

WriteLiteral(" data-tippy-dropdown-content=\"\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                    <svg");

WriteLiteral(" class=\"icon icon-dots stock-table__control-icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                        <use");

WriteAttribute("href", Tuple.Create(" href=\"", 13054), Tuple.Create("\"", 13119)
            
            #line 192 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 13061), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#dots")
            
            #line default
            #line hidden
, 13061), false)
);

WriteLiteral("></use>\r\n                                    </svg>\r\n                            " +
"        <div");

WriteLiteral(" data-tippy-dropdown-content-template=\"\"");

WriteLiteral(">\r\n                                        <ul");

WriteLiteral(" class=\"tooltip-nav\"");

WriteLiteral(">\r\n                                            <li");

WriteLiteral(" class=\"tooltip-nav__item\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"tooltip-nav__link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 197 "..\..\Views\Order\List.cshtml"
                                                                                 Write(SharedResources.DeleteOrder);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                            </li>\r\n                        " +
"                    <li");

WriteLiteral(" class=\"tooltip-nav__item\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"tooltip-nav__link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 200 "..\..\Views\Order\List.cshtml"
                                                                                 Write(SharedResources.RepeatOrder);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                            </li>\r\n                        " +
"                    <li");

WriteLiteral(" class=\"tooltip-nav__item\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"tooltip-nav__link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 203 "..\..\Views\Order\List.cshtml"
                                                                                 Write(SharedResources.PrintAPP);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                            </li>\r\n                        " +
"                    <li");

WriteLiteral(" class=\"tooltip-nav__item\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"tooltip-nav__link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 206 "..\..\Views\Order\List.cshtml"
                                                                                 Write(SharedResources.ExportToExcel);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div");

WriteLiteral(" class=\"stock-table__inner js-accordion-body\"");

WriteLiteral(" data-loaded=\"false\"");

WriteLiteral(" data-orderId=\"");

            
            #line 214 "..\..\Views\Order\List.cshtml"
                                                                                                       Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" hidden>\r\n                            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 14669), Tuple.Create("\"", 14694)
, Tuple.Create(Tuple.Create("", 14674), Tuple.Create("updateBlock-", 14674), true)
            
            #line 215 "..\..\Views\Order\List.cshtml"
, Tuple.Create(Tuple.Create("", 14686), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 14686), false)
);

WriteLiteral(">\r\n                                <p>");

            
            #line 216 "..\..\Views\Order\List.cshtml"
                              Write(SharedResources.Loading);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            </div>\r\n\r\n                            ");

WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 222 "..\..\Views\Order\List.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n\r\n");

            
            #line 227 "..\..\Views\Order\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 227 "..\..\Views\Order\List.cshtml"
       Html.RenderPartial("OrderListMob", Model); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"stock-area__bottom\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"stock-area__pagination pagination\"");

WriteLiteral(">\r\n");

            
            #line 231 "..\..\Views\Order\List.cshtml"
            
            
            #line default
            #line hidden
            
            #line 231 "..\..\Views\Order\List.cshtml"
              Html.RenderPartial("Components/Pagination", Model.Orders);
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("BreadCrumbs", () => {

WriteLiteral("\r\n");

            
            #line 237 "..\..\Views\Order\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 237 "..\..\Views\Order\List.cshtml"
      Html.RenderPartial("Components/BreadCrumbsRender", new List<BreadCrumbsModel> { new BreadCrumbsModel { Name = SharedResources.Orders }});
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Filters", () => {

WriteLiteral("\r\n");

            
            #line 241 "..\..\Views\Order\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 241 "..\..\Views\Order\List.cshtml"
       Html.RenderPartial("OrderFilter", Model.Filters); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

            
            #line 245 "..\..\Views\Order\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 245 "..\..\Views\Order\List.cshtml"
      Html.RenderPartial("_OrderListScripts");
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 246 "..\..\Views\Order\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 246 "..\..\Views\Order\List.cshtml"
       Html.RenderPartial("GridViewFooterScripts", Model.Orders); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
