#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Order\OrderHeaderPartial.cshtml"
    using ValmiStore.Model.Entities.Order;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Order\OrderHeaderPartial.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/OrderHeaderPartial.cshtml")]
    public partial class _Views_Order_OrderHeaderPartial_cshtml : System.Web.Mvc.WebViewPage<Order>
    {
        public _Views_Order_OrderHeaderPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 6 "..\..\Views\Order\OrderHeaderPartial.cshtml"
  
    var draftSatuses = new[] { (int)OrderStatuses.Draft, (int)OrderStatuses.SendedToProcess };
    var onStockSatuses = new[] { (int)OrderStatuses.Packaging, (int)OrderStatuses.ReadyForDelivery };

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 11 "..\..\Views\Order\OrderHeaderPartial.cshtml"
Write(SharedResources.Order);

            
            #line default
            #line hidden
WriteLiteral(" № ");

            
            #line 11 "..\..\Views\Order\OrderHeaderPartial.cshtml"
                        Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n");

WriteLiteral("\n<div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\n");

        }
    }
}
#pragma warning restore 1591
