#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Order\PaymentRejection.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/PaymentRejection.cshtml")]
    public partial class _Views_Order_PaymentRejection_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.Payments.PaymentModel>
    {
        public _Views_Order_PaymentRejection_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Order\PaymentRejection.cshtml"
  
    ViewBag.Title = SharedResources.PaymentRejected;
    Layout = "~/Views/Shared/_PersonalLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n<aside");

WriteLiteral(" id=\"catalog-content\"");

WriteLiteral(">\n");

            
            #line 10 "..\..\Views\Order\PaymentRejection.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Order\PaymentRejection.cshtml"
     if (Model.Order != null) { Html.RenderPartial("OrderHeaderPartial", Model.Order); }

            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(" id=\"pageBreadscrumbs\"");

WriteLiteral(">\n        <li><span");

WriteLiteral(" id=\"bs1\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Order\PaymentRejection.cshtml"
                      Write(SharedResources.WareSelection);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\n        <li>&#8250;</li>\n        <li><span");

WriteLiteral(" id=\"bs2\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Order\PaymentRejection.cshtml"
                      Write(SharedResources.PaymentForm);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\n        <li>&#8250;</li>\n        <li><span");

WriteLiteral(" id=\"bs3\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Order\PaymentRejection.cshtml"
                      Write(SharedResources.Delivery);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\n        <li>&#8250;</li>\n        <li><span");

WriteLiteral(" id=\"bs4\"");

WriteLiteral(" class=\"current\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Order\PaymentRejection.cshtml"
                                      Write(SharedResources.OrderCompleting);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\n    </ul>\n\n    <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\n    <div");

WriteLiteral(" class=\"invoice-wrapper\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"invoice\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"invoice-border\"");

WriteLiteral(">\n                <a");

WriteLiteral(" id=\"logo-small\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 901), Tuple.Create("\"", 959)
            
            #line 25 "..\..\Views\Order\PaymentRejection.cshtml"
, Tuple.Create(Tuple.Create("", 907), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ExtContent/images/logo-invoice.png")
            
            #line default
            #line hidden
, 907), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral("> </a>\n                <h2>");

            
            #line 26 "..\..\Views\Order\PaymentRejection.cshtml"
               Write(SharedResources.OrderPayment);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n                <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\n\n                <div");

WriteLiteral(" class=\"payment-error\"");

WriteLiteral(">\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Order\PaymentRejection.cshtml"
                Write(new HtmlString(string.Format(SharedResources.PaymentErrorMessage, Model.OrderId, Model.Amount, Url.Action("Order", "Order", new { id = Model.OrderId, showPaymentFirst = true }))));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n\n");

            
            #line 33 "..\..\Views\Order\PaymentRejection.cshtml"
                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Order\PaymentRejection.cshtml"
                 if (Model.Order != null) { Html.RenderPartial("_SummaryOrderInfo", Model.Order); }

            
            #line default
            #line hidden
WriteLiteral("\n                <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\n\n            </div>\n        </div>\n");

            
            #line 39 "..\..\Views\Order\PaymentRejection.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Order\PaymentRejection.cshtml"
           Html.RenderPartial("_SummaryVidgets"); 
            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</aside>");

        }
    }
}
#pragma warning restore 1591
