#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 2 "..\..\Views\Order\Payment.cshtml"
    using ValmiStore.Model.Entities.Order;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Order\Payment.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Order\Payment.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 4 "..\..\Views\Order\Payment.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/Payment.cshtml")]
    public partial class _Views_Order_Payment_cshtml : System.Web.Mvc.WebViewPage<Order>
    {
        public _Views_Order_Payment_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Order\Payment.cshtml"
  
    ViewBag.Title = SharedResources.Payment;
    Layout = "~/Views/Shared/_PersonalLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<aside");

WriteLiteral(" id=\"catalog-content\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\Order\Payment.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Order\Payment.cshtml"
       Html.RenderPartial("OrderHeaderPartial", Model); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <ul");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(" id=\"pageBreadscrumbs\"");

WriteLiteral(">\r\n        <li><span");

WriteLiteral(" id=\"bs1\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Order\Payment.cshtml"
                      Write(SharedResources.WareSelection);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n        <li>&#8250;</li>\r\n        <li><span");

WriteLiteral(" id=\"bs2\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Order\Payment.cshtml"
                      Write(SharedResources.PaymentForm);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n        <li>&#8250;</li>\r\n        <li><span");

WriteLiteral(" id=\"bs3\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Order\Payment.cshtml"
                      Write(SharedResources.Delivery);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n        <li>&#8250;</li>\r\n        <li><span");

WriteLiteral(" id=\"bs4\"");

WriteLiteral(" class=\"current\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Order\Payment.cshtml"
                                      Write(SharedResources.OrderCompleting);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n    </ul>\r\n\r\n    <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\r\n    <div");

WriteLiteral(" class=\"invoice-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"invoice\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"invoice-border\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" id=\"logo-small\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 942), Tuple.Create("\"", 1000)
            
            #line 30 "..\..\Views\Order\Payment.cshtml"
, Tuple.Create(Tuple.Create("", 948), Tuple.Create<System.Object, System.Int32>(Url.Content("~/ExtContent/images/logo-invoice.png")
            
            #line default
            #line hidden
, 948), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral("> </a>\r\n                <h2>");

            
            #line 31 "..\..\Views\Order\Payment.cshtml"
               Write(SharedResources.OrderPayment);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Order\Payment.cshtml"
            Write(new HtmlString(string.Format(SharedResources.PaymentTitle2, Model.Id, (string.IsNullOrEmpty(Model.ResponsibleName)) ? ConfigHelper.SummaryManager : Model.ResponsibleName, ConfigHelper.SummaryManagerPhone)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 35 "..\..\Views\Order\Payment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Order\Payment.cshtml"
                   Html.RenderPartial("_SummaryOrderInfo", Model); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\r\n\r\n");

            
            #line 39 "..\..\Views\Order\Payment.cshtml"
                
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Order\Payment.cshtml"
                 if (Model.PaymentType == (int)PaymentTypes.Visa)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"center\"");

WriteLiteral(" style=\"margin-top:20px; display:inline-block;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 42 "..\..\Views\Order\Payment.cshtml"
                   Write(Html.Button(SharedResources.VisaPayment, new { onclick = "return VisaPaymentExecute()", id = "VisaPaymentButton" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n");

            
            #line 44 "..\..\Views\Order\Payment.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 45 "..\..\Views\Order\Payment.cshtml"
                 if (Model.PaymentType == (int)PaymentTypes.LiqPay)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"center\"");

WriteLiteral(" style=\"margin-top:20px; display:inline-block;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 48 "..\..\Views\Order\Payment.cshtml"
                   Write(Html.Button(SharedResources.LiqPayment, new { onclick = "return VisaPaymentExecute()", id = "LiqPaymentButton" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n");

            
            #line 50 "..\..\Views\Order\Payment.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 51 "..\..\Views\Order\Payment.cshtml"
                 if (Model.PaymentType == (int) PaymentTypes.Invoice)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"pdf-big clickable\"");

WriteLiteral(" onclick=\"return InvoicePaymentExecute(\'PDF\')\"");

WriteLiteral(">");

            
            #line 53 "..\..\Views\Order\Payment.cshtml"
                                                                                          Write(SharedResources.GetPDFInvoice);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" class=\"xls-big clickable\"");

WriteLiteral(" onclick=\"return InvoicePaymentExecute(\'EXCEL\')\"");

WriteLiteral(">");

            
            #line 54 "..\..\Views\Order\Payment.cshtml"
                                                                                            Write(SharedResources.GetExcelInvoice);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 55 "..\..\Views\Order\Payment.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"clear-div\"");

WriteLiteral("> </div>\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"button-submit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2738), Tuple.Create("\"", 2767)
            
            #line 60 "..\..\Views\Order\Payment.cshtml"
, Tuple.Create(Tuple.Create("", 2746), Tuple.Create<System.Object, System.Int32>(SharedResources.Next
            
            #line default
            #line hidden
, 2746), false)
);

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2768), Tuple.Create("\"", 2884)
, Tuple.Create(Tuple.Create("", 2778), Tuple.Create("window.location=\'", 2778), true)
            
            #line 60 "..\..\Views\Order\Payment.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2795), Tuple.Create<System.Object, System.Int32>(Url.Action("Summary", "Order", new { orderId = Model.Id, paymentId=Model.PaymentType })
            
            #line default
            #line hidden
, 2795), false)
, Tuple.Create(Tuple.Create("", 2883), Tuple.Create("\'", 2883), true)
);

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 63 "..\..\Views\Order\Payment.cshtml"
        
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Order\Payment.cshtml"
           Html.RenderPartial("_SummaryVidgets"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</aside>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        function InvoicePaymentExecute(reportFormat) {\r\n            var orderI" +
"d = \'");

            
            #line 71 "..\..\Views\Order\Payment.cshtml"
                      Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var url = \"");

            
            #line 72 "..\..\Views\Order\Payment.cshtml"
                  Write(Url.Action("InvoicePayment", "Reports"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            var params = \"?orderId=\" + orderId + \"&reportFormat=\" + reportFor" +
"mat;\r\n            window.open(url + params);\r\n            return false;\r\n       " +
" }\r\n\r\n        function VisaPaymentExecute() {\r\n            var orderId = \'");

            
            #line 79 "..\..\Views\Order\Payment.cshtml"
                      Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var url = \"");

            
            #line 80 "..\..\Views\Order\Payment.cshtml"
                   Write(Url.Action("Payment", "Order"));

            
            #line default
            #line hidden
WriteLiteral("?orderId=\" + orderId;\r\n            document.location.href = url;\r\n            ret" +
"urn false;\r\n        }\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
