#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Components\NewsArticle.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Components/NewsArticle.cshtml")]
    public partial class _Views_Shared_Components_NewsArticle_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.ViewModel.News.NewsArticleViewModel>
    {
        public _Views_Shared_Components_NewsArticle_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Components\NewsArticle.cshtml"
  
    var article = Model.Article;
    var newsUrl = Url.Action("Index", "News", new { category = Model.Category?.Slug, id = article.Url });

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-6 col-md-3\"");

WriteLiteral(">\r\n    <article");

WriteLiteral(" class=\"news\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"news__img-wrap\"");

WriteAttribute("href", Tuple.Create(" href=\"", 314), Tuple.Create("\"", 329)
            
            #line 11 "..\..\Views\Shared\Components\NewsArticle.cshtml"
, Tuple.Create(Tuple.Create("", 321), Tuple.Create<System.Object, System.Int32>(newsUrl
            
            #line default
            #line hidden
, 321), false)
);

WriteLiteral("><img");

WriteLiteral(" class=\"news__img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 353), Tuple.Create("\"", 455)
            
            #line 11 "..\..\Views\Shared\Components\NewsArticle.cshtml"
, Tuple.Create(Tuple.Create("", 359), Tuple.Create<System.Object, System.Int32>(article.ImageUrl.StartsWith("http") ? article.ImageUrl : Url.Content("~/" + article.ImageUrl)
            
            #line default
            #line hidden
, 359), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 456), Tuple.Create("\"", 477)
            
            #line 11 "..\..\Views\Shared\Components\NewsArticle.cshtml"
                                                                                                      , Tuple.Create(Tuple.Create("", 462), Tuple.Create<System.Object, System.Int32>(article.Header
            
            #line default
            #line hidden
, 462), false)
);

WriteLiteral("></a>\r\n        <div");

WriteLiteral(" class=\"news__body\"");

WriteLiteral(">\r\n            <time");

WriteLiteral(" class=\"news__date\"");

WriteLiteral(" datetime=\"2019-08-16\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Shared\Components\NewsArticle.cshtml"
                                                      Write(article.Date.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n            <div");

WriteLiteral(" class=\"news__title\"");

WriteLiteral("><a");

WriteLiteral(" class=\"news__title-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 684), Tuple.Create("\"", 699)
            
            #line 14 "..\..\Views\Shared\Components\NewsArticle.cshtml"
, Tuple.Create(Tuple.Create("", 691), Tuple.Create<System.Object, System.Int32>(newsUrl
            
            #line default
            #line hidden
, 691), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Views\Shared\Components\NewsArticle.cshtml"
                                                                            Write(article.ShortText);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n");

            
            #line 15 "..\..\Views\Shared\Components\NewsArticle.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\Components\NewsArticle.cshtml"
             if (Model.Category?.Slug != "news")
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" class=\"news__more-btn btn btn--primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 854), Tuple.Create("\"", 869)
            
            #line 17 "..\..\Views\Shared\Components\NewsArticle.cshtml"
, Tuple.Create(Tuple.Create("", 861), Tuple.Create<System.Object, System.Int32>(newsUrl
            
            #line default
            #line hidden
, 861), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Views\Shared\Components\NewsArticle.cshtml"
                                                                      Write(SharedResources.Details);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 18 "..\..\Views\Shared\Components\NewsArticle.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </article>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
