#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Components\Product.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Components\Product.cshtml"
    using Webmall.Model.Entities.Catalog;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 3 "..\..\Views\Shared\Components\Product.cshtml"
    using Webmall.UI.Core.HtmlHelpers;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Components/Product.cshtml")]
    public partial class _Views_Shared_Components_Product_cshtml : System.Web.Mvc.WebViewPage<WareListItem>
    {
        public _Views_Shared_Components_Product_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\Components\Product.cshtml"
  
    var imgUrl = Model.ImageUrl ?? (Model.HasImage ? Url.WareImage(Model.ImageId) : "~/assets/images/general/product-default.jpg");

            
            #line default
            #line hidden
WriteLiteral("\r\n<article");

WriteLiteral(" class=\"product-card catalog__item\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"product-card__wrapper\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" class=\"product-card__header\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"product-card__img-wrap\"");

WriteAttribute("href", Tuple.Create(" href=\"", 433), Tuple.Create("\"", 450)
            
            #line 12 "..\..\Views\Shared\Components\Product.cshtml"
, Tuple.Create(Tuple.Create("", 440), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 440), false)
);

WriteLiteral(">\r\n                <img");

WriteLiteral(" class=\"product-card__img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 500), Tuple.Create("\"", 528)
            
            #line 13 "..\..\Views\Shared\Components\Product.cshtml"
, Tuple.Create(Tuple.Create("", 506), Tuple.Create<System.Object, System.Int32>(Url.Content(imgUrl)
            
            #line default
            #line hidden
, 506), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 529), Tuple.Create("\"", 546)
            
            #line 13 "..\..\Views\Shared\Components\Product.cshtml"
  , Tuple.Create(Tuple.Create("", 535), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 535), false)
);

WriteLiteral(">\r\n            </a>\r\n            \r\n            <img");

WriteLiteral(" class=\"product-card__logo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 625), Tuple.Create("\"", 671)
            
            #line 16 "..\..\Views\Shared\Components\Product.cshtml"
, Tuple.Create(Tuple.Create("", 631), Tuple.Create<System.Object, System.Int32>(Url.ProducerImage(Model.ProducerName)
            
            #line default
            #line hidden
, 631), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 672), Tuple.Create("\"", 697)
            
            #line 16 "..\..\Views\Shared\Components\Product.cshtml"
                 , Tuple.Create(Tuple.Create("", 678), Tuple.Create<System.Object, System.Int32>(Model.ProducerName
            
            #line default
            #line hidden
, 678), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 698), Tuple.Create("\"", 725)
            
            #line 16 "..\..\Views\Shared\Components\Product.cshtml"
                                             , Tuple.Create(Tuple.Create("", 706), Tuple.Create<System.Object, System.Int32>(Model.ProducerName
            
            #line default
            #line hidden
, 706), false)
);

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\Shared\Components\Product.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\Components\Product.cshtml"
               Html.RenderPartial("Components/WareActionLabel", Model); 
            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"product-card__informers\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Shared\Components\Product.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Shared\Components\Product.cshtml"
                 if (Model.Producer?.IsRecommended == true)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"product-card__informer badge\"");

WriteLiteral(" data-tippy-content=\"");

            
            #line 21 "..\..\Views\Shared\Components\Product.cshtml"
                                                                              Write(SharedResources.IsRecommended);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <svg");

WriteLiteral(" class=\"icon icon-like badge__icon\"");

WriteLiteral("><use");

WriteAttribute("href", Tuple.Create(" href=\"", 1120), Tuple.Create("\"", 1185)
            
            #line 22 "..\..\Views\Shared\Components\Product.cshtml"
, Tuple.Create(Tuple.Create("", 1127), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#like")
            
            #line default
            #line hidden
, 1127), false)
);

WriteLiteral("></use></svg>\r\n                    </span>\r\n");

            
            #line 24 "..\..\Views\Shared\Components\Product.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" class=\"product-card__informer badge\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                    <svg");

WriteLiteral(" class=\"icon icon-scales-add product__informer-icon\"");

WriteLiteral("><use");

WriteAttribute("href", Tuple.Create(" href=\"", 1397), Tuple.Create("\"", 1468)
            
            #line 26 "..\..\Views\Shared\Components\Product.cshtml"
        , Tuple.Create(Tuple.Create("", 1404), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#scales-add")
            
            #line default
            #line hidden
, 1404), false)
);

WriteLiteral("></use></svg>\r\n                </a>\r\n            </div>\r\n        </header>\r\n     " +
"   <div");

WriteLiteral(" class=\"product-card__body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"product-card__title\"");

WriteLiteral("><a");

WriteLiteral(" class=\"product-card__title-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1667), Tuple.Create("\"", 1684)
            
            #line 31 "..\..\Views\Shared\Components\Product.cshtml"
       , Tuple.Create(Tuple.Create("", 1674), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 1674), false)
);

WriteLiteral(">");

            
            #line 31 "..\..\Views\Shared\Components\Product.cshtml"
                                                                                              Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n            <div");

WriteLiteral(" class=\"product-card__info\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"product-card__brand\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Shared\Components\Product.cshtml"
                                            Write(Model.ProducerName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"product-card__articul\"");

WriteLiteral(" data-template-articul=\"art-1\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"product-card__articul-text\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Shared\Components\Product.cshtml"
                                                       Write(Model.WareNumber);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n                <div");

WriteLiteral(" data-tooltip-content=\"art-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"product-card__articul-tooltip\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Shared\Components\Product.cshtml"
                                                          Write(Model.WareNumber);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n            <a");

WriteLiteral(" class=\"product-card__add btn btn--primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2286), Tuple.Create("\"", 2303)
            
            #line 41 "..\..\Views\Shared\Components\Product.cshtml"
, Tuple.Create(Tuple.Create("", 2293), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 2293), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Views\Shared\Components\Product.cshtml"
                                                                       Write(SharedResources.Details);

            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("</a>\r\n            <div");

WriteLiteral(" class=\"product-card__footer\"");

WriteLiteral(">\r\n                <dl");

WriteLiteral(" class=\"product-card__params\"");

WriteLiteral(" data-ware-id=\"");

            
            #line 43 "..\..\Views\Shared\Components\Product.cshtml"
                                                          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("id", Tuple.Create(" id=\"", 2581), Tuple.Create("\"", 2605)
, Tuple.Create(Tuple.Create("", 2586), Tuple.Create("tile_spec_", 2586), true)
            
            #line 43 "..\..\Views\Shared\Components\Product.cshtml"
        , Tuple.Create(Tuple.Create("", 2596), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 2596), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"product-card__param\"");

WriteLiteral(">\r\n                        <dt");

WriteLiteral(" class=\"product-card__property\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Shared\Components\Product.cshtml"
                                                      Write(SharedResources.Loading);

            
            #line default
            #line hidden
WriteLiteral(" ...</dt>\r\n                        <dd");

WriteLiteral(" class=\"product-card__value\"");

WriteLiteral("></dd>\r\n                    </div>\r\n                </dl>\r\n            </div>\r\n  " +
"      </div>\r\n        <div");

WriteLiteral(" class=\"product-card__more-trigger\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"product-card__more-trigger-btn js-mob-extra-trigger\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"product-card__more-trigger-text\"");

WriteLiteral(">");

            
            #line 53 "..\..\Views\Shared\Components\Product.cshtml"
                                                         Write(SharedResources.Specifications);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <svg");

WriteLiteral(" class=\"icon icon-chevron-down product-card__more-trigger-icon\"");

WriteLiteral("><use");

WriteAttribute("href", Tuple.Create(" href=\"", 3230), Tuple.Create("\"", 3303)
            
            #line 54 "..\..\Views\Shared\Components\Product.cshtml"
               , Tuple.Create(Tuple.Create("", 3237), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#chevron-down")
            
            #line default
            #line hidden
, 3237), false)
);

WriteLiteral("></use></svg>\r\n            </button>\r\n        </div>\r\n    </div>\r\n</article>");

        }
    }
}
#pragma warning restore 1591
