#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 2 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Components/TopHeaderNav.cshtml")]
    public partial class _Views_Shared_Components_TopHeaderNav_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Components_TopHeaderNav_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"top-informer\"");

WriteLiteral(" hidden>\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"top-informer__main\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"top-informer__about\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"top-informer__caption\"");

WriteLiteral(" id=\"informer-caption\"");

WriteLiteral("></div>\r\n                <p");

WriteLiteral(" class=\"top-informer__desc\"");

WriteLiteral(" id=\"informer-desc\"");

WriteLiteral("></p>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"top-informer__bottom\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" data-modal-win-trigger=\"modal-locations\"");

WriteLiteral(" class=\"top-informer__btn btn btn--primary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                                                                                                           Write(SharedResources.ViewItems);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </div>\r\n            <button");

WriteLiteral(" class=\"top-informer__close\"");

WriteLiteral(" id=\"informer-close\"");

WriteLiteral(">\r\n                <svg");

WriteLiteral(" class=\"icon icon-close top-informer__close-icon\"");

WriteLiteral(">\r\n                    <use");

WriteAttribute("href", Tuple.Create(" href=\"", 780), Tuple.Create("\"", 846)
            
            #line 20 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
, Tuple.Create(Tuple.Create("", 787), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#close")
            
            #line default
            #line hidden
, 787), false)
);

WriteLiteral("></use>\r\n                </svg>\r\n            </button>\r\n        </div>\r\n    </div" +
">\r\n</div>\r\n\r\n");

            
            #line 27 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
  Html.RenderAction("ContactHeader", "Layout", new { culture = UserPreferences.CurrentCulture });
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var deniedAccessGeodata = \"");

            
            #line 30 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                              Write(SharedResources.DeniedAccessGeodata);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var deliveryPoint = \"");

            
            #line 31 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                        Write(SharedResources.DeliveryPoint);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var identifiedStoreClosest = \"");

            
            #line 32 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                                 Write(SharedResources.IdentifiedStoreClosest);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var chooseAnotherDeliveryPoint = \"");

            
            #line 33 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                                     Write(SharedResources.ChooseAnotherDeliveryPoint);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var linkGetCitys = \"/\"+\"");

            
            #line 34 "..\..\Views\Shared\Components\TopHeaderNav.cshtml"
                           Write(UserPreferences.CurrentCultureLink);

            
            #line default
            #line hidden
WriteLiteral("\" + \"Home/GetCitys\";\r\n</script>");

        }
    }
}
#pragma warning restore 1591
