#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/OriginalCatalog/_SideBar.cshtml")]
    public partial class _Views_OriginalCatalog__SideBar_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.ExternalCatalogModel>
    {
        public _Views_OriginalCatalog__SideBar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"category-nav d-none d-md-block\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"category-nav__list\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
             foreach (var category in Model.Catalog)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 251), Tuple.Create("\"", 334)
, Tuple.Create(Tuple.Create("", 259), Tuple.Create("category-nav__item", 259), true)
            
            #line 8 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
, Tuple.Create(Tuple.Create(" ", 277), Tuple.Create<System.Object, System.Int32>(category.Slug == Model.SelectedItemId ? "active" : ""
            
            #line default
            #line hidden
, 278), false)
);

WriteLiteral("><a");

WriteLiteral(" class=\"category-nav__link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 365), Tuple.Create("\"", 420)
            
            #line 8 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
                                                             , Tuple.Create(Tuple.Create("", 372), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { Id = category.Slug })
            
            #line default
            #line hidden
, 372), false)
);

WriteLiteral(">");

            
            #line 8 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
                                                                                                                                                                                         Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 9 "..\..\Views\OriginalCatalog\_SideBar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
