#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 2 "..\..\Views\Promotions\Show.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Promotions\Show.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Promotions/Show.cshtml")]
    public partial class _Views_Promotions_Show_cshtml : System.Web.Mvc.WebViewPage<Webmall.Model.Entities.Cms.NewsData.NewsArticle>
    {
        public _Views_Promotions_Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Promotions\Show.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = ViewBag.NewsType;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"breadcrumbs__item\"");

WriteLiteral("><a");

WriteLiteral(" class=\"breadcrumbs__link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 314), Tuple.Create("\"", 338)
            
            #line 12 "..\..\Views\Promotions\Show.cshtml"
, Tuple.Create(Tuple.Create("", 321), Tuple.Create<System.Object, System.Int32>(Url.Content("~")
            
            #line default
            #line hidden
, 321), false)
);

WriteLiteral(">");

            
            #line 12 "..\..\Views\Promotions\Show.cshtml"
                                                                                       Write(SharedResources.MainPage);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        <li");

WriteLiteral(" class=\"breadcrumbs__item\"");

WriteLiteral("><a");

WriteLiteral(" class=\"breadcrumbs__link\"");

WriteLiteral(" href=\"./../\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Promotions\Show.cshtml"
                                                                           Write(title);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        <li");

WriteLiteral(" class=\"breadcrumbs__item\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Promotions\Show.cshtml"
                                 Write(Model.Header);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n    <div");

WriteLiteral(" class=\"inner-section__header\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" class=\"inner-section__heading\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Promotions\Show.cshtml"
                                      Write(SharedResources.Promotions);

            
            #line default
            #line hidden
WriteLiteral("</h1><a");

WriteLiteral(" class=\"inner-section__link\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Promotions\Show.cshtml"
                                                                                                              Write(Model.Header);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"primary-content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"category-nav d-none d-md-block\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"category-nav__list\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"category-nav__item\"");

WriteLiteral("><a");

WriteLiteral(" class=\"category-nav__link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 982), Tuple.Create("\"", 1017)
            
            #line 23 "..\..\Views\Promotions\Show.cshtml"
        , Tuple.Create(Tuple.Create("", 989), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "News")
            
            #line default
            #line hidden
, 989), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\Promotions\Show.cshtml"
                                                                                                                Write(SharedResources.News);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                    <li");

WriteLiteral(" class=\"category-nav__item\"");

WriteLiteral("><a");

WriteLiteral(" class=\"category-nav__link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1131), Tuple.Create("\"", 1172)
            
            #line 24 "..\..\Views\Promotions\Show.cshtml"
       , Tuple.Create(Tuple.Create("", 1138), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Promotions")
            
            #line default
            #line hidden
, 1138), false)
);

WriteLiteral(">");

            
            #line 24 "..\..\Views\Promotions\Show.cshtml"
                                                                                                                      Write(SharedResources.Promotions);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <ma" +
"in");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"inner-news\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"data\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Promotions\Show.cshtml"
                           Write(Model.Date.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Promotions\Show.cshtml"
            Write(new HtmlString(Model.FullText));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Promotions\Show.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Promotions\Show.cshtml"
                 if (ConfigHelper.AllowSocialShare)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"socialbookmarks-content\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Promotions\Show.cshtml"
                   Write(SharedResources.DoYouLikeShare);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"//yastatic.net/share/share.js\"");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral("></script>\r\n                        <span");

WriteLiteral(" class=\"yashare-auto-init\"");

WriteLiteral(" data-yasharel10n=\"ru\"");

WriteLiteral(" data-yasharetype=\"none\"");

WriteLiteral(" data-yasharequickservices=\"facebook,twitter,vkontakte\"");

WriteLiteral("></span>\r\n                    </div>\r\n");

            
            #line 40 "..\..\Views\Promotions\Show.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"prev-next\"");

WriteLiteral(">\r\n");

            
            #line 42 "..\..\Views\Promotions\Show.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Promotions\Show.cshtml"
                     if (Model.PrevId != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2125), Tuple.Create("\"", 2190)
            
            #line 44 "..\..\Views\Promotions\Show.cshtml"
, Tuple.Create(Tuple.Create("", 2132), Tuple.Create<System.Object, System.Int32>(Url.Action("Show", "Promotions", new {id = Model.PrevId})
            
            #line default
            #line hidden
, 2132), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 2196), Tuple.Create("\"", 2244)
            
            #line 44 "..\..\Views\Promotions\Show.cshtml"
                       , Tuple.Create(Tuple.Create("", 2202), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/images/start.gif")
            
            #line default
            #line hidden
, 2202), false)
);

WriteLiteral(" width=\"8\"");

WriteLiteral(" height=\"9\"");

WriteLiteral("></a>\r\n");

WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2299), Tuple.Create("\"", 2364)
            
            #line 45 "..\..\Views\Promotions\Show.cshtml"
, Tuple.Create(Tuple.Create("", 2306), Tuple.Create<System.Object, System.Int32>(Url.Action("Show", "Promotions", new {id = Model.PrevId})
            
            #line default
            #line hidden
, 2306), false)
);

WriteLiteral(">");

            
            #line 45 "..\..\Views\Promotions\Show.cshtml"
                                                                                        Write(SharedResources.PrevNews);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 46 "..\..\Views\Promotions\Show.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 47 "..\..\Views\Promotions\Show.cshtml"
                     if (Model.NextId != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2517), Tuple.Create("\"", 2582)
            
            #line 49 "..\..\Views\Promotions\Show.cshtml"
, Tuple.Create(Tuple.Create("", 2524), Tuple.Create<System.Object, System.Int32>(Url.Action("Show", "Promotions", new {id = Model.NextId})
            
            #line default
            #line hidden
, 2524), false)
);

WriteLiteral(">");

            
            #line 49 "..\..\Views\Promotions\Show.cshtml"
                                                                                        Write(SharedResources.NextNews);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2641), Tuple.Create("\"", 2706)
            
            #line 50 "..\..\Views\Promotions\Show.cshtml"
, Tuple.Create(Tuple.Create("", 2648), Tuple.Create<System.Object, System.Int32>(Url.Action("Show", "Promotions", new {id = Model.NextId})
            
            #line default
            #line hidden
, 2648), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 2712), Tuple.Create("\"", 2761)
            
            #line 50 "..\..\Views\Promotions\Show.cshtml"
                       , Tuple.Create(Tuple.Create("", 2718), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/images/finish.gif")
            
            #line default
            #line hidden
, 2718), false)
);

WriteLiteral(" width=\"8\"");

WriteLiteral(" height=\"9\"");

WriteLiteral("></a>\r\n");

            
            #line 51 "..\..\Views\Promotions\Show.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n        </main>\r\n    </div>\r\n</div>\r\n" +
"\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 59 "..\..\Views\Promotions\Show.cshtml"
Write(Styles.Render("~/Content/fancybox/fancy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "..\..\Views\Promotions\Show.cshtml"
Write(Scripts.Render("~/bundles/fancy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
