#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 2 "..\..\Views\Lxm\FilterDialog.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 1 "..\..\Views\Lxm\FilterDialog.cshtml"
    using Webmall.UI.Models.Laximo;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Lxm/FilterDialog.cshtml")]
    public partial class _Views_Lxm_FilterDialog_cshtml : System.Web.Mvc.WebViewPage<UnitModel>
    {
        public _Views_Lxm_FilterDialog_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 6 "..\..\Views\Lxm\FilterDialog.cshtml"
  
    var baseModel = Model.Clone();
    baseModel.UnitId = Model.UnitInfo.Id;
    baseModel.Ssd = Model.Ssd;

            
            #line default
            #line hidden
WriteLiteral("\n\n<div");

WriteLiteral(" id=\"dialogLxmFilter\"");

WriteLiteral(" title=\"2.0 TDI\"");

WriteLiteral(@"></div>

<script>
    $(function () {

        $(""#dialogLxmFilter"").dialog({
            autoOpen: false,
            resizable: false,
            draggable: true,
            width: ""auto"",
            minHeight: 50,
            show: {
                effect: ""fade"",
                duration: 100
            },
            hide: {
                effect: ""explode"",
                duration: 500
            }
        }
        );
    });

    function ViewInfo(obj) {
        var title = '");

            
            #line 36 "..\..\Views\Lxm\FilterDialog.cshtml"
                Write(SharedResources.SelectFromList);

            
            #line default
            #line hidden
WriteLiteral(@"';
        $('#dialogLxmFilter').dialog(""option"", ""title"", title);
        $(""#dialogLxmFilter"").dialog(""open"");
        $('#dialogLxmFilter').dialog(""widget"").position({
            my: ""left top"",
            at: ""right bottom"",
            of: obj
        });
    }

    function UpdateInfo(obj) {
        //var id = obj.id;
        var filter = (obj.attributes.filter) ? obj.attributes.filter.value : null;
        updatePannel('");

            
            #line 49 "..\..\Views\Lxm\FilterDialog.cshtml"
                 Write(Html.Raw(Url.Action("Filter", baseModel)));

            
            #line default
            #line hidden
WriteLiteral("\'+\'&filter=\'+filter, \'dialogLxmFilter\', null, ViewInfo, obj);\n    }\n\n</script>");

        }
    }
}
#pragma warning restore 1591
