#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    #line 1 "..\..\Views\Lxm\VinSearch.cshtml"
    using Webmall.UI.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Lxm/VinSearch.cshtml")]
    public partial class _Views_Lxm_VinSearch_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.Models.Laximo.VehicleListModel>
    {
        public _Views_Lxm_VinSearch_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Lxm\VinSearch.cshtml"
  
    // ViewBag.Title = ((Model != null && Model.Wares.List != null && Model.Wares.List.Any())) ? SharedResources.Search + ": " + ViewBag.SearchBy ?? SharedResources.byProperties : SharedResources.NothingFound2Title;
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Lxm\VinSearch.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Lxm\VinSearch.cshtml"
      Html.RenderPartial("Components/BreadCrumbsRender", new List<BreadCrumbsModel> { new BreadCrumbsModel { Name = Model.Vin } });
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"vinsearch-layout\"");

WriteLiteral(">\r\n        <aside");

WriteLiteral(" class=\"vinsearch-layout__aside\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"table-responsive media-card-info__wrap\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\Lxm\VinSearch.cshtml"
                
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Lxm\VinSearch.cshtml"
                   Html.RenderPartial("_VinSearchHistory", Model.SearchHistory); 
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </aside>\r\n        <main");

WriteLiteral(" class=\"vinsearch-layout__main\"");

WriteLiteral(" role=\"main\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Lxm\VinSearch.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Lxm\VinSearch.cshtml"
             if (!Model.Vehicles.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"vin-search-hist vin-search-hist-table d-none d-md-block\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Lxm\VinSearch.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Lxm\VinSearch.cshtml"
                     if (TempData["Message"] != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <h1>");

            
            #line 25 "..\..\Views\Lxm\VinSearch.cshtml"
                        Write(TempData["Message"]);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 26 "..\..\Views\Lxm\VinSearch.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");

            
            #line 28 "..\..\Views\Lxm\VinSearch.cshtml"
            }
            else
            {
                Html.RenderPartial("_VehiclesCards", Model);

            
            #line default
            #line hidden
WriteLiteral("                <br/>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"stock-area__mob-table stock-mob-table js-checked-all is-table-mode\"");

WriteLiteral(">\r\n");

            
            #line 34 "..\..\Views\Lxm\VinSearch.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Lxm\VinSearch.cshtml"
                       Html.RenderPartial("_VinSearchHistory", Model.SearchHistory); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 36 "..\..\Views\Lxm\VinSearch.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </main>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
