#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Layout\Dialogs\_LocationsDialog.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    using Webmall.UI;
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Layout/Dialogs/_LocationsDialog.cshtml")]
    public partial class _Views_Layout_Dialogs__LocationsDialog_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Layout_Dialogs__LocationsDialog_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" data-modal-win=\"modal-locations\"");

WriteLiteral(" hidden>\r\n    <div");

WriteLiteral(" class=\"modal-content__heading modal-win-title\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Layout\Dialogs\_LocationsDialog.cshtml"
                                                   Write(SharedResources.StoreSelection);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    <div");

WriteLiteral(" class=\"modal-content__body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content__locations\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content__locations-subsection\"");

WriteLiteral(">\r\n                <div>\r\n                    <div");

WriteLiteral(" class=\"modal-content__locations-caption\"");

WriteLiteral(">\r\n                        <svg");

WriteLiteral(" class=\"icon icon-location\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                            <use");

WriteAttribute("href", Tuple.Create(" href=\"", 536), Tuple.Create("\"", 605)
            
            #line 11 "..\..\Views\Layout\Dialogs\_LocationsDialog.cshtml"
, Tuple.Create(Tuple.Create("", 543), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/svg/symbol/sprite.svg#location")
            
            #line default
            #line hidden
, 543), false)
);

WriteLiteral("></use>\r\n                        </svg>\r\n");

WriteLiteral("                        ");

            
            #line 13 "..\..\Views\Layout\Dialogs\_LocationsDialog.cshtml"
                   Write(SharedResources.PickupNearestShops);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <ul");

WriteLiteral(" class=\"modal-content__locations-list\"");

WriteLiteral(" id=\"locations-list\"");

WriteLiteral(@"></ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function SetCity(city_id, short_name) {
        $(""#current-location"").text(short_name);
        var today = new Date();
        var expire = new Date();
        var nDays = 365;

        expire.setTime(today.getTime() + 3600000 * 24 * nDays);
        document.cookie = ""CityId"" + ""="" + escape(city_id) + "";expires="" + expire.toGMTString();

        $("".modal-win__close"").click();
        $("".mob-regions__close"").click();
        $(""#informer-close"").click();
    }
</script>");

        }
    }
}
#pragma warning restore 1591
