#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    using Webmall.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Layout/StickyHeader.cshtml")]
    public partial class _Views_Layout_StickyHeader_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Layout_StickyHeader_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Layout\StickyHeader.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"header__sticky sticky-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sticky-header__main\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"logo sticky-header__logo\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"logo__wrap\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"logo__img img-responsive\"");

WriteLiteral(" src=\"assets/images/logo.svg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"190\"");

WriteLiteral(" height=\"60\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" />\r\n                </span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n");

        }
    }
}
#pragma warning restore 1591
