#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 2 "..\..\Views\Security\PasswordRecovery.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Security\PasswordRecovery.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 3 "..\..\Views\Security\PasswordRecovery.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/PasswordRecovery.cshtml")]
    public partial class _Views_Security_PasswordRecovery_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.ViewModel.Security.PasswordRecoveryViewModel>
    {
        public _Views_Security_PasswordRecovery_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Security\PasswordRecovery.cshtml"
  
    ViewBag.Title = SecurityResources.AccessRecovery;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <!-- restore-->\r\n        <div");

WriteLiteral(" class=\"restore\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"restore__img-wrap\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" class=\"restore__img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 392), Tuple.Create("\"", 450)
            
            #line 15 "..\..\Views\Security\PasswordRecovery.cshtml"
, Tuple.Create(Tuple.Create("", 398), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/restore-password.svg")
            
            #line default
            #line hidden
, 398), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"620\"");

WriteLiteral(" height=\"640\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"restore__main\"");

WriteLiteral(">\r\n                <!-- restore-form-->\r\n                <div");

WriteLiteral(" class=\"restore__form restore-form\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"restore-form__img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 693), Tuple.Create("\"", 739)
            
            #line 20 "..\..\Views\Security\PasswordRecovery.cshtml"
, Tuple.Create(Tuple.Create("", 699), Tuple.Create<System.Object, System.Int32>(Url.Content("~/assets/images/lock.svg")
            
            #line default
            #line hidden
, 699), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"620\"");

WriteLiteral(" height=\"640\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"restore-form__heading\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Security\PasswordRecovery.cshtml"
                                                  Write(SecurityResources.AccessRecovery);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 22 "..\..\Views\Security\PasswordRecovery.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Security\PasswordRecovery.cshtml"
                     using (Html.BeginForm("PasswordRecovery", "Security", FormMethod.Post, new { id = "recovery-form", @class = "restore-form__main" }))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Security\PasswordRecovery.cshtml"
                                    Write(Html.ValidationSummary(true, SharedResources.ErrorsFound));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("                        <div");

WriteLiteral(" class=\"restore-form__fields\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"restore-form__fields\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"restore-form__field\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"restore-form__caption\"");

WriteLiteral(" for=\"login\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 29 "..\..\Views\Security\PasswordRecovery.cshtml"
                                   Write(Html.Raw(Model.Label));

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span>\r\n                                    </label>\r\n                  " +
"                  <input");

WriteLiteral(" class=\"restore-form__input input\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"login\"");

WriteLiteral(" id=\"login\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1669), Tuple.Create("\"", 1689)
            
            #line 31 "..\..\Views\Security\PasswordRecovery.cshtml"
                                        , Tuple.Create(Tuple.Create("", 1677), Tuple.Create<System.Object, System.Int32>(Model.Login
            
            #line default
            #line hidden
, 1677), false)
);

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"restore-form__field\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"RecaptchaPasswordRecovery\"");

WriteLiteral("></div>\r\n                                    ");

WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n");

WriteLiteral("                        <div");

WriteLiteral(" class=\"restore-form__bottom\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" class=\"restore-form__btn btn btn--primary\"");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2538), Tuple.Create("\"", 2576)
            
            #line 43 "..\..\Views\Security\PasswordRecovery.cshtml"
                   , Tuple.Create(Tuple.Create("", 2546), Tuple.Create<System.Object, System.Int32>(SecurityResources.SendRequest
            
            #line default
            #line hidden
, 2546), false)
);

WriteLiteral(">\r\n                        </div>\r\n");

            
            #line 45 "..\..\Views\Security\PasswordRecovery.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"restore-form__notification info\"");

WriteLiteral(">\r\n                        <p>\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\Views\Security\PasswordRecovery.cshtml"
                       Write(Html.Raw(Model.Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </p>\r\n                    </div>\r\n                </div" +
"><!-- /restore-form-->\r\n            </div>\r\n        </div><!-- /restore-->\r\n    " +
"</div>\r\n</div>\r\n\r\n\r\n");

WriteLiteral("\r\n\r\n");

DefineSection("headerScript", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"//www.google.com/recaptcha/api.js?onload=CaptchaCallback&render=explicit\"");

WriteLiteral(" async defer></script>\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            $(""#recovery-form"").validate({
                rules: {
                    Email: {
                        required: true,
                        email: true
                    }
                }
            });
        });
    </script>
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var CaptchaCallback = function () {\r\n            window.grecaptcha.ren" +
"der(\'RecaptchaPasswordRecovery\', { \'sitekey\': \'");

            
            #line 116 "..\..\Views\Security\PasswordRecovery.cshtml"
                                                                           Write(ConfigHelper.CaptchaSiteKey);

            
            #line default
            #line hidden
WriteLiteral("\' });\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
