#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\CatalogService\OffersTableMob.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\CatalogService\OffersTableMob.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    #line 3 "..\..\Views\CatalogService\OffersTableMob.cshtml"
    using Webmall.UI.Core;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\CatalogService\OffersTableMob.cshtml"
    using Webmall.UI.Core.HtmlHelpers;
    
    #line default
    #line hidden
    using Webmall.UI.Core.Localization;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CatalogService/OffersTableMob.cshtml")]
    public partial class _Views_CatalogService_OffersTableMob_cshtml : System.Web.Mvc.WebViewPage<Webmall.UI.ViewModel.Catalog.OffersViewModel>
    {
        public _Views_CatalogService_OffersTableMob_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\CatalogService\OffersTableMob.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\CatalogService\OffersTableMob.cshtml"
 if (Model.Offers.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"mob-data-table__heading\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                    Write(Model.Caption);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 15 "..\..\Views\CatalogService\OffersTableMob.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"mob-data-table__products\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\CatalogService\OffersTableMob.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\CatalogService\OffersTableMob.cshtml"
          var count = 0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 18 "..\..\Views\CatalogService\OffersTableMob.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\CatalogService\OffersTableMob.cshtml"
         foreach (var off in Model.Offers)
        {
            count++;
            var imgUrl = off.Ware.HasImage ? Url.WareImage(off.Ware.Id) : "~/assets/images/general/product-default.jpg";
                

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 582), Tuple.Create("\"", 664)
, Tuple.Create(Tuple.Create("", 590), Tuple.Create("mob-data-table__product", 590), true)
, Tuple.Create(Tuple.Create(" ", 613), Tuple.Create("data-table-product", 614), true)
            
            #line 23 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create(" ", 632), Tuple.Create<System.Object, System.Int32>(count > 5 ? "is-hidden" : ""
            
            #line default
            #line hidden
, 633), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"data-table-product__header\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"data-table-product__badges\"");

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                         if (off.Ware.HasImage)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"data-table__badge badge js-item-gallery\"");

WriteAttribute("href", Tuple.Create(" href=\"", 944), Tuple.Create("\"", 973)
            
            #line 28 "..\..\Views\CatalogService\OffersTableMob.cshtml"
         , Tuple.Create(Tuple.Create("", 951), Tuple.Create<System.Object, System.Int32>(Url.Content(imgUrl)
            
            #line default
            #line hidden
, 951), false)
);

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <svg");

WriteLiteral(" class=\"icon icon-photo badge__icon stock-table__product-img\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(" data-template=\"");

            
            #line 30 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                                                                   Write(off.Ware.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                    <use");

WriteAttribute("href", Tuple.Create(" href=\"", 1362), Tuple.Create("\"", 1429)
            
            #line 31 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 1369), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#photo")
            
            #line default
            #line hidden
, 1369), false)
);

WriteLiteral("></use>\r\n                                </svg>\r\n                                " +
"");

WriteLiteral("\r\n                                <div");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                                    ");

WriteLiteral("\r\n                                    <div");

WriteLiteral(" class=\"tooltip-content\"");

WriteAttribute("Id", Tuple.Create(" Id=\"", 2111), Tuple.Create("\"", 2146)
, Tuple.Create(Tuple.Create("", 2116), Tuple.Create("WareImagePannel_", 2116), true)
            
            #line 40 "..\..\Views\CatalogService\OffersTableMob.cshtml"
      , Tuple.Create(Tuple.Create("", 2132), Tuple.Create<System.Object, System.Int32>(off.Ware.Id
            
            #line default
            #line hidden
, 2132), false)
);

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n");

            
            #line 43 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                        }
                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                              

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 50 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                         if (off.IsReplacement)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"data-table__badge badge\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-modal-win-trigger=\"number-info\"");

WriteLiteral(">\r\n                                <svg");

WriteLiteral(" class=\"icon icon-undo badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                    <use");

WriteAttribute("href", Tuple.Create(" href=\"", 3003), Tuple.Create("\"", 3069)
            
            #line 54 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 3010), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#undo")
            
            #line default
            #line hidden
, 3010), false)
);

WriteLiteral("></use>\r\n                                </svg>\r\n                            </a>" +
"\r\n");

            
            #line 57 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 58 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                         if (off.AllowAddToCompare)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"data-table__badge badge\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                <svg");

WriteLiteral(" class=\"icon icon-scales-add badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                    <use");

WriteAttribute("href", Tuple.Create(" href=\"", 3477), Tuple.Create("\"", 3549)
            
            #line 62 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 3484), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#scales-add")
            
            #line default
            #line hidden
, 3484), false)
);

WriteLiteral("></use>\r\n                                </svg>\r\n                            </a>" +
"\r\n");

            
            #line 65 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"data-table__badge badge\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3718), Tuple.Create("\"", 3781)
            
            #line 66 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 3725), Tuple.Create<System.Object, System.Int32>(off.IsReplacement ? Url.Ware(off.Ware) : "#section-1"
            
            #line default
            #line hidden
, 3725), false)
);

WriteLiteral(">\r\n                            <svg");

WriteLiteral(" class=\"icon icon-info badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 3914), Tuple.Create("\"", 3980)
            
            #line 68 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 3921), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#info")
            
            #line default
            #line hidden
, 3921), false)
);

WriteLiteral("></use>\r\n                            </svg>\r\n                        </a>\r\n      " +
"                  ");

WriteLiteral("\r\n                    </div>\r\n");

            
            #line 82 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                     if (off.Ware.Producer?.IsRecommended == true)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"data-table-product__recommend badge\"");

WriteLiteral(" data-tippy-content=\"");

            
            #line 84 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                         Write(SharedResources.IsRecommended);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                            <svg");

WriteLiteral(" class=\"icon icon-like badge__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 5164), Tuple.Create("\"", 5230)
            
            #line 86 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 5171), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#like")
            
            #line default
            #line hidden
, 5171), false)
);

WriteLiteral("></use>\r\n                            </svg>\r\n                        </span>\r\n");

            
            #line 89 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n                <div");

WriteLiteral(" class=\"data-table-product__main\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"data-table-product__meta\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"data-table-product__articul\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                  Write(off.Ware.WareNumber);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        <a");

WriteLiteral(" class=\"data-table-product__brand\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">");

            
            #line 94 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                Write(off.Ware.ProducerName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"data-table-product__heading\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"data-table-product__heading-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5824), Tuple.Create("\"", 5883)
, Tuple.Create(Tuple.Create("", 5831), Tuple.Create("/Catalog/", 5831), true)
            
            #line 97 "..\..\Views\CatalogService\OffersTableMob.cshtml"
   , Tuple.Create(Tuple.Create("", 5840), Tuple.Create<System.Object, System.Int32>(off.Ware.ProducerName
            
            #line default
            #line hidden
, 5840), false)
, Tuple.Create(Tuple.Create("", 5862), Tuple.Create("/", 5862), true)
            
            #line 97 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                          , Tuple.Create(Tuple.Create("", 5863), Tuple.Create<System.Object, System.Int32>(off.Ware.WareNumber
            
            #line default
            #line hidden
, 5863), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 98 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                       Write(off.Ware.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </div>\r\n                    <" +
"div");

WriteLiteral(" class=\"data-table-product__table data-product-table\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"data-product-table__header\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"data-product-table__row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__caption\"");

WriteLiteral(">");

            
            #line 105 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                        Write(SharedResources.Stock);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__caption\"");

WriteLiteral(">");

            
            #line 108 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                        Write(SharedResources.Amount);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__caption\"");

WriteLiteral(">");

            
            #line 111 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                        Write(SharedResources.TermDays);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__caption\"");

WriteLiteral(">");

            
            #line 114 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                        Write(SharedResources.PurchasePrice);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__caption\"");

WriteLiteral(">&nbsp;</div>\r\n                                </div>\r\n                          " +
"  </div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"data-product-table__main\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"data-product-table__row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__stickers\"");

WriteLiteral(">\r\n");

            
            #line 125 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 125 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                         if (off.Ware.IsSale)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"data-product-table__sticker sticker is-discount\"");

WriteLiteral(">Распродажа</div>\r\n");

            
            #line 128 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        ");

            
            #line 129 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                         if (off.Ware.InAction)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"data-product-table__sticker sticker is-action\"");

WriteLiteral(">Акция</div>\r\n");

            
            #line 132 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        ");

            
            #line 133 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                         if (off.Ware.IsNew)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"data-product-table__sticker sticker is-new\"");

WriteLiteral(">");

            
            #line 135 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                               Write(SharedResources.NewWare);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 136 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                    <" +
"div");

WriteLiteral(" class=\"data-product-table__location\"");

WriteLiteral(">");

            
            #line 138 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                         Write(off.Offer.SupplierWarehouseName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__progress progress-badge is-success\"");

WriteLiteral(">");

            
            #line 139 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                                    Write(off.Offer.DeliveryRating);

            
            #line default
            #line hidden
WriteLiteral("%</div>\r\n                                </div>\r\n                                " +
"<div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__text\"");

WriteLiteral(">");

            
            #line 142 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                      Write(off.Offer.AvailableQntStr);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__term term-info\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"term-info__text\"");

WriteLiteral(">");

            
            #line 146 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                 Write(off.Offer.DeliveryTerm.ToString("dd.MM"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <div");

WriteLiteral(" class=\"term-info__availability\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"term-info__availability-text\"");

WriteLiteral(">");

            
            #line 148 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                  Write(off.Offer.DeliveryDays);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                            <svg");

WriteLiteral(" class=\"icon icon-stock term-info__availability-icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 9682), Tuple.Create("\"", 9749)
            
            #line 150 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 9689), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#stock")
            
            #line default
            #line hidden
, 9689), false)
);

WriteLiteral("></use>\r\n                                            </svg>\r\n                    " +
"                    </div>\r\n                                    </div>\r\n        " +
"                        </div>\r\n                                <div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__prices\"");

WriteLiteral(">\r\n                                        <strong");

WriteLiteral(" class=\"data-product-table__price-primary\"");

WriteLiteral(">");

            
            #line 157 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                      Write(off.Offer.ClientPrice.ToString(Model.PriceFormat));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                        <span");

WriteLiteral(" class=\"data-product-table__price-secondary\"");

WriteLiteral(">");

            
            #line 158 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                                      Write(off.Offer.ClientSalePrice.ToString(Model.PriceFormat));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                    </div>\r\n                            " +
"    </div>\r\n                                <div");

WriteLiteral(" class=\"data-product-table__cell\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"data-product-table__action\"");

WriteLiteral(">\r\n");

            
            #line 163 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 163 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                          
                                            var p = $"{off.Ware.Id},'{off.Offer.Id}',{off.Offer.ClientPrice.ToString().Replace(",", ".")},'{off.Ware.WareNumber}','{off.Ware.ProducerName}'";
                                            var func = SessionHelper.CurrentUser != null ? $"AddToCart(this, {p})" : $"AddToCartLocal(this, {p})";
                                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <a");

WriteLiteral(" class=\"data-product-table__control action-control\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 11154), Tuple.Create("\"", 11178)
, Tuple.Create(Tuple.Create("", 11164), Tuple.Create("return", 11164), true)
            
            #line 167 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                             , Tuple.Create(Tuple.Create(" ", 11170), Tuple.Create<System.Object, System.Int32>(func
            
            #line default
            #line hidden
, 11171), false)
);

WriteLiteral(">\r\n                                            <svg");

WriteLiteral(" class=\"icon icon-shopping-cart action-control__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                                                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 11361), Tuple.Create("\"", 11436)
            
            #line 169 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 11368), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#shopping-cart")
            
            #line default
            #line hidden
, 11368), false)
);

WriteLiteral("></use>\r\n                                            </svg>\r\n                    " +
"                        <small");

WriteLiteral(" class=\"action-control__info\"");

WriteLiteral(">");

            
            #line 171 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                                                           Write(off.InCart);

            
            #line default
            #line hidden
WriteLiteral(@"</small>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
");

            
            #line 180 "..\..\Views\CatalogService\OffersTableMob.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 182 "..\..\Views\CatalogService\OffersTableMob.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"mob-data-table__bottom\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"mob-data-table__more js-more-btn btn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-more-text=\"Показать еще\"");

WriteLiteral("\r\n                data-less-text=\"Скрыть\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"btn__text\"");

WriteLiteral(">Показать еще</span>\r\n            <svg");

WriteLiteral(" class=\"icon icon-chevron-down btn__icon\"");

WriteLiteral(" width=\"25\"");

WriteLiteral(" height=\"25\"");

WriteLiteral(">\r\n                <use");

WriteAttribute("href", Tuple.Create(" href=\"", 12244), Tuple.Create("\"", 12318)
            
            #line 188 "..\..\Views\CatalogService\OffersTableMob.cshtml"
, Tuple.Create(Tuple.Create("", 12251), Tuple.Create<System.Object, System.Int32>(Url.Content("/assets/images/svg/symbol/sprite.svg#chevron-down")
            
            #line default
            #line hidden
, 12251), false)
);

WriteLiteral("></use>\r\n            </svg>\r\n        </button>\r\n    </div>\r\n");

            
            #line 192 "..\..\Views\CatalogService\OffersTableMob.cshtml"

    
            
            #line default
            #line hidden
            
            #line 319 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                


}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"data-table__subsection js-more-parent\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"data-table__subheading\"");

WriteLiteral(">");

            
            #line 326 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                                       Write(Model.Caption);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n        <div");

WriteLiteral(" class=\"data-table__row\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"SortDir\"");

WriteLiteral(" name=\"SortDir\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"SortColumn\"");

WriteLiteral(" name=\"SortColumn\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"data-table__cell\"");

WriteLiteral(">\r\n                <span>");

            
            #line 333 "..\..\Views\CatalogService\OffersTableMob.cshtml"
                 Write(SharedResources.NoData);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 337 "..\..\Views\CatalogService\OffersTableMob.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
