#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HtmlHelpers.BeginCollectionItem;
    
    #line 1 "..\..\Views\Article\Index.cshtml"
    using ViewRes;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Article\Index.cshtml"
    using Webmall.Model;
    
    #line default
    #line hidden
    using Webmall.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Article/Index.cshtml")]
    public partial class _Views_Article_Index_cshtml : System.Web.Mvc.WebViewPage<Webmall.Model.Entities.Cms.Article>
    {
        public _Views_Article_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Article\Index.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.Header;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <main");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"primary\"");

WriteLiteral(">\r\n            <main");

WriteLiteral(" class=\"primary__main\"");

WriteLiteral(">\r\n                <!-- article-->\r\n                <article");

WriteLiteral(" class=\"article\"");

WriteLiteral(">\r\n                    <header");

WriteLiteral(" class=\"article__header\"");

WriteLiteral(">\r\n                        <h1");

WriteLiteral(" class=\"article__heading\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Article\Index.cshtml"
                                                Write(Model.Header);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                    </header>\r\n                    <div");

WriteLiteral(" class=\"article__main\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"article__content post-entry\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 22 "..\..\Views\Article\Index.cshtml"
                       Write(Html.Raw(Model.FullText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 24 "..\..\Views\Article\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Article\Index.cshtml"
                         if (ConfigHelper.AllowSocialShare)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"article__share\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"article__share-link share-link\"");

WriteLiteral(" href=\"\"");

WriteLiteral(">\r\n                                    <script");

WriteLiteral(" src=\"https://yastatic.net/share2/share.js\"");

WriteLiteral("></script>\r\n                                    <div");

WriteLiteral(" class=\"ya-share2\"");

WriteLiteral(" data-curtain");

WriteLiteral(" data-size=\"m\"");

WriteLiteral(" data-shape=\"round\"");

WriteLiteral(" data-services=\"facebook,telegram,twitter\"");

WriteLiteral("></div>\r\n                                    ");

WriteLiteral("\r\n                                    ");

WriteLiteral("\r\n                                    <span");

WriteLiteral(" class=\"share-link__text\"");

WriteLiteral(">&nbsp; ");

            
            #line 35 "..\..\Views\Article\Index.cshtml"
                                                                     Write(SharedResources.DoYouLikeShare);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </a>\r\n                            </div>" +
"\r\n");

            
            #line 38 "..\..\Views\Article\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </article><!-- /article-->\r\n         " +
"   </main>\r\n        </div>\r\n    </main>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 60 "..\..\Views\Article\Index.cshtml"
Write(Styles.Render("~/Content/fancybox/fancy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "..\..\Views\Article\Index.cshtml"
Write(Scripts.Render("~/bundles/fancy"));

            
            #line default
            #line hidden
WriteLiteral(@"
    <script>
        $(""a[rel=images].fancy"").fancybox({
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'titlePosition': 'inside',
            'titleFormat': function (title, currentArray, currentIndex, currentOpts) {
                var url = $(currentArray[currentIndex]).attr('url');
                return ""<span id='fancybox-title-inside' class='hand' onclick=document.location.href='"" + url + ""'>"" + title + ""</span>"";
            }
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
