//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValmiStore.Resources.SecurityResources", typeof(SecurityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление доступа.
        /// </summary>
        public static string AccessRecovery {
            get {
                return ResourceManager.GetString("AccessRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только администраторы.
        /// </summary>
        public static string AdminsOnly {
            get {
                return ResourceManager.GetString("AdminsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to всех пользователей.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить фильтр.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string AreYouForgetPassword {
            get {
                return ResourceManager.GetString("AreYouForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось попыток.
        /// </summary>
        public static string AttemptsRemain {
            get {
                return ResourceManager.GetString("AttemptsRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное имя пользователя или пароль.
        /// </summary>
        public static string BadPasswordOrLogin {
            get {
                return ResourceManager.GetString("BadPasswordOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите операцию.
        /// </summary>
        public static string ConfirmOperation {
            get {
                return ResourceManager.GetString("ConfirmOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите, что Вы не робот.
        /// </summary>
        public static string ConfirmYouAreNotRobot {
            get {
                return ResourceManager.GetString("ConfirmYouAreNotRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенный Email уже зарегистрирован.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер карточки клиента (при указании более одного номера, вводить через запятую).
        /// </summary>
        public static string FiscCodesTitle {
            get {
                return ResourceManager.GetString("FiscCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к управлению представительствами.
        /// </summary>
        public static string GotoPresentationsManagement {
            get {
                return ResourceManager.GetString("GotoPresentationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в течение.
        /// </summary>
        public static string InTime {
            get {
                return ResourceManager.GetString("InTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридические лица.
        /// </summary>
        public static string JuridicalPersons {
            get {
                return ResourceManager.GetString("JuridicalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только менеджеры.
        /// </summary>
        public static string ManagersOnly {
            get {
                return ResourceManager.GetString("ManagersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to минут.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация нового пользователя.
        /// </summary>
        public static string NewUserRegistration {
            get {
                return ResourceManager.GetString("NewUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент еще не зарегистрирован. Свяжитесь с менеджером..
        /// </summary>
        public static string NoClientsRegistered {
            get {
                return ResourceManager.GetString("NoClientsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to только заблокированных.
        /// </summary>
        public static string OnlyBlocked {
            get {
                return ResourceManager.GetString("OnlyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to только незаблокированных.
        /// </summary>
        public static string OnlyUnblocked {
            get {
                return ResourceManager.GetString("OnlyUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль? Бывает. &lt;br /&gt;
        ///    Введите Ваш еmail, указанный при регистрации, и мы вышлем Вам на него Ваш новый пароль. Изменить свой пароль Вы сможете в «Моем кабинете» во вкладке «Профиль/Смена пароля»..
        /// </summary>
        public static string PasswordRecoveryMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физические лица.
        /// </summary>
        public static string PhisicalPersons {
            get {
                return ResourceManager.GetString("PhisicalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прочитать.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение регистрации.
        /// </summary>
        public static string RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код клиента {0} - {1}.
        /// </summary>
        public static string RepresentationRequestErrorRow {
            get {
                return ResourceManager.GetString("RepresentationRequestErrorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При регистрации представительств произошли следующие ошибки:.
        /// </summary>
        public static string RepresentationRequestErrorTitle {
            get {
                return ResourceManager.GetString("RepresentationRequestErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор системы безопасности.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер по общим вопросам.
        /// </summary>
        public static string RoleCallManager {
            get {
                return ResourceManager.GetString("RoleCallManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер каталога.
        /// </summary>
        public static string RoleCatalogManager {
            get {
                return ResourceManager.GetString("RoleCatalogManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер по работе с клиентами.
        /// </summary>
        public static string RoleClientManager {
            get {
                return ResourceManager.GetString("RoleClientManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КСМ.
        /// </summary>
        public static string RoleClientServiceManager {
            get {
                return ResourceManager.GetString("RoleClientServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер контента.
        /// </summary>
        public static string RoleContentManager {
            get {
                return ResourceManager.GetString("RoleContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер мероприятий.
        /// </summary>
        public static string RoleEventManager {
            get {
                return ResourceManager.GetString("RoleEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к программе лояльности.
        /// </summary>
        public static string RoleLoyaltyUser {
            get {
                return ResourceManager.GetString("RoleLoyaltyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер по ключевым сотрудникам.
        /// </summary>
        public static string RoleRepresentativeManager {
            get {
                return ResourceManager.GetString("RoleRepresentativeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string RoleStatistic {
            get {
                return ResourceManager.GetString("RoleStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ-менеджер по работе с клиентами.
        /// </summary>
        public static string RoleTopClientManager {
            get {
                return ResourceManager.GetString("RoleTopClientManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просто пользователь.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер по VIN-запросам.
        /// </summary>
        public static string RoleVINRequestManager {
            get {
                return ResourceManager.GetString("RoleVINRequestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я ознакомлен и принимаю условия пользовательского соглашения, договора публичной оферты  и регламента гарантии.
        /// </summary>
        public static string SelectAgreementFlag {
            get {
                return ResourceManager.GetString("SelectAgreementFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить запрос.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодарим за регистрацию.
        /// </summary>
        public static string ThanksForRegistration {
            get {
                return ResourceManager.GetString("ThanksForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ожидание подтверждения.
        /// </summary>
        public static string WaitingConfirmation {
            get {
                return ResourceManager.GetString("WaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы не согласились с условиями договора.
        /// </summary>
        public static string WrongAgreementFlag {
            get {
                return ResourceManager.GetString("WrongAgreementFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код с картинки введен неверно. &lt;a href=&quot;&quot; onclick=&quot;history.back()&quot; style=&quot;font-weight: bolder&quot; class=&quot;hand&quot;&gt;Вернуться &lt;/a&gt;.
        /// </summary>
        public static string WrongCAPTCHA {
            get {
                return ResourceManager.GetString("WrongCAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют фискальные коды клиентов.
        /// </summary>
        public static string WrongClientCodes {
            get {
                return ResourceManager.GetString("WrongClientCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Email..
        /// </summary>
        public static string WrongEmailAddress {
            get {
                return ResourceManager.GetString("WrongEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населенный пункт не найден.
        /// </summary>
        public static string WrongLocality {
            get {
                return ResourceManager.GetString("WrongLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to старый пароль введен неверно.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль задан неверно.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код введен неверно.
        /// </summary>
        public static string WrongPin {
            get {
                return ResourceManager.GetString("WrongPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы не прошли проверку, что Вы не робот.
        /// </summary>
        public static string WrongRecaptchaSimpleMessage {
            get {
                return ResourceManager.GetString("WrongRecaptchaSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не представляете клиента.
        /// </summary>
        public static string YouAreNotPresentClient {
            get {
                return ResourceManager.GetString("YouAreNotPresentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись заблокирована. Обратитесь к администратору сайта..
        /// </summary>
        public static string YourAccountIsLocked {
            get {
                return ResourceManager.GetString("YourAccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись не подтверждена. Проверьте почту и перейдите по ссылке в присланном нами письме для подтверждения регистрации (письмо может попасть в папку &quot;Спам&quot;).
        /// </summary>
        public static string YourAccountWaitsConfirmation {
            get {
                return ResourceManager.GetString("YourAccountWaitsConfirmation", resourceCulture);
            }
        }
    }
}
